### ISSUE TITLE
Version sorting of 0.5.0 is broken

### ISSUE THREAD

**Issue by bmerry** [lebedov/scikit-cuda#115]
In setuptools versioning, 0.5.0b2 is considered to sort *before* 0.42. Thus, even with a requirement like `scikits.cuda>=0.5.0b1`, I get 0.42 installed. I suggest labelling the release as 0.50 rather than 0.5.0 to fix this.

**Comment by lebedov** [comment]
Given that 0.42 is quite old and I plan to [rename the package to scikit-cuda](https://github.com/lebedov/scikit-cuda/issues/45) this summer in any event, I would prefer to remove the former from pypi rather than jump to version 0.50.

**Comment by lebedov** [comment]
Package renamed and updated to 0.5.0. I removed the old versions from pypi.
