### ISSUE TITLE
AssertionError assert isinstance(shape, (int, int, np.integer))

### ISSUE THREAD

**Issue by Benli11** [lebedov/scikit-cuda#131]
Hello,

I just have set up Scikit-Cuda on Windows 10 with CUDA Toolkit 7.0 and CULA R18.
Now, when I am trying to compute a SVD with the following example:

> import pycuda.gpuarray as gpuarray
> import pycuda.autoinit
> import numpy as np
> import skcuda.linalg
> linalg.init()
> a = np.random.randn(9, 9) 
> a = np.asarray(a, np.float32)
> a_gpu = gpuarray.to_gpu(a)
> u_gpu, s_gpu, vh_gpu = linalg.svd(a_gpu, 'S', 'S')

I get the following error:
> Traceback (most recent call last):
> File "<ipython-input-30-61a6ecde00ba>", line 9, in <module>
    u_gpu, s_gpu, vh_gpu = linalg.svd(a_gpu, 'S', 'S')
>
>  File "C:\Users\ben\Anaconda\lib\site-packages\scikit_cuda-0.5.1-py2.7.egg\skcuda\linalg.py", line 148, in svd
>    s_gpu = gpuarray.empty(min(m, n), real_type, allocator=alloc)
>
>  File "C:\Users\ben\Anaconda\lib\site-packages\pycuda-2015.1.3-py2.7-win-amd64.egg\pycuda\gpuarray.py", line 170, in __init__
    assert isinstance(shape, (int, int, np.integer))
>
> AssertionError

The problem I guess is that the data type of 
> n, m = a_gpu.shape
is long and not int.

So I was able to fix the problem by

> n, m = np.array(a_gpu.shape, int)

Cheers,
B

**Comment by lebedov** [comment]
What version of Python are you using? I can't reproduce this with scikit-cuda revision 207a634 on Linux with Python 2.7.10 and pycuda 2015.1.3. In any case, I suspect that this may be an issue with pycuda - it seems odd to for `int` to appear twice in the `isinstance` check. I'll follow up with the pycuda developer.

**Comment by Benli11** [comment]
Yes agreed, it is a bit strange...

Python 2.7.10 :: Anaconda 2.3.0 (64-bit)
PyCUDA (2015, 1, 3

**Comment by lebedov** [comment]
Can you check what the types of the contents of `a_gpu.shape` actually are before the call to `linalg.svd`?

**Comment by Benli11** [comment]
>...: A = np.random.randn(5, 5) 
>...: A = np.array(A, np.float32, order='F')
>...: a_gpu = gpuarray.to_gpu(A)
>...: a_gpu.shape
> Out[24]: (5L, 5L)

It is of type: long integer object

**Comment by lebedov** [comment]
This seems to be due to Windows: see https://github.com/numpy/numpy/issues/5809.

**Comment by Benli11** [comment]
Annoying... so I will use
> n, m = np.array(a_gpu.shape, int)

as a quick&dirty fix.

**Comment by lebedov** [comment]
Yes - I'll leave this issue open until I apply the quick fix to the other skcuda functions that look at array shape.

**Comment by lebedov** [comment]
The underlying issue was [just fixed](https://github.com/inducer/pycuda/commit/743d66450ba2f106bb2c157b8ba108c400461499) in pycuda.
