### ISSUE TITLE
Any chance cuDNN will be supported?

### ISSUE THREAD

**Issue by kuprel** [lebedov/scikit-cuda#135]
Not really an issue, but it would be awesome if cuDNN was supported

**Comment by lebedov** [comment]
Hans Bretschneider [has written](https://github.com/hannes-brt/cudnn-python-wrappers) cuDNN Python wrappers in essentially the same style as that employed by scikit-cuda that you might want to check out. I'm certainly open to incorporating them into scikit-cuda (preferably with Hans' permission), although I don't currently have the time to prepare any high-level interfaces for them.
