### ISSUE TITLE
CUDA version 7.5 compatibility

### ISSUE THREAD

**Issue by orangeduck** [lebedov/scikit-cuda#142]
I've been using this library with CUDA 7.5 by adding 7.5 to the `_version_list` variable in most of the skcuda files. It appears to be working fine so I was considering submitting a patch but I know nothing about this library so I'm unsure if/how it might break things.

Can anyone who knows more say if this is okay?

**Comment by lebedov** [comment]
I just updated the `_version_list` variables accordingly. If you encounter any weirdness when using skcuda with CUDA 7.5, feel free to submit more issue reports.

**Comment by orangeduck** [comment]
Will do, thanks!
