### ISSUE TITLE
skcuda.misc.var: Bessel's correction

### ISSUE THREAD

**Issue by Stefannn** [lebedov/scikit-cuda#143]
Hi, 
I think there's an error in the computation of the variance in the skcuda.misc.var function. The current implementation does not use the unbiased estimator of the variance, i.e.
sum_{j=1}^N \frac{x_j-mean(x)}{n-1} [unbiased]
instead of 
sum_{j=1}^N \frac{x_j-mean(x)}{n} [biased]

**Comment by lebedov** [comment]
`skcuda.misc.var()` computes the uncorrected variance to mimic the behavior of `numpy.var()`, which doesn't apply the Bessel correction by default. That said, it would be a good idea to enable the user to specify whether to apply as `numpy.var()` does.

**Comment by lebedov** [comment]
Also updated `skcuda.misc.std()` to permit optional use of the Bessel correction.
