### ISSUE TITLE
SVD Demo not compiling

### ISSUE THREAD

**Issue by zevektor** [lebedov/scikit-cuda#144]
I'm using scikit-cuda 0.5.0 on a Linux machine with Anacoda set to run Python 3.4

I've double checked that I'm satisfying all the [dependencies](http://scikit-cuda.readthedocs.org/en/latest/install.html#installation-dependencies).

I was trying to run the svd demo, but I keep getting this error from linalg.py
```
Traceback (most recent call last):
  File "/home/vektor/PycharmProjects/yancut/forabettersvd.py", line 12, in <module>
    import skcuda.linalg as culinalg
  File "/home/vektor/anaconda3/lib/python3.4/site-packages/skcuda/linalg.py", line 43, in <module>
    from . import install_headers
ImportError: cannot import name 'install_headers'
```

**Comment by zevektor** [comment]
After installing 0.5.1 from fix-pip-install branch it works.

**Comment by lebedov** [comment]
Thanks for reporting this - I merged the branch and posted a new release.
