### ISSUE TITLE
culaDeviceSorgqr on python 2.7

### ISSUE THREAD

**Issue by gul916** [lebedov/scikit-cuda#146]
Hi,
I am using scikit-cuda, under windows 7 64 bits with an NIVIDIA GTX 660 graphic card. Here are the packages installed:
- Visual studio community 2013 update 5
- Cuda toolkit 7.5
- Cula R18 free edition
- Python 2.7.10 64 bits
- Numpy-1.10.1+mkl.whl
- Scipy-0.16.1.whl
- Pycuda-2015.1.3+cuda7518.whl from http://www.lfd.uci.edu/~gohlke/pythonlibs/
- Scikit-cuda-0.5.1 has been installed using pip.

I am getting an error when using test_fft.py:

c:\Program Files\Python27\lib\site-packages\skcuda\cublas.py:272: UserWarning: creating CUBLAS context to get version number
  warnings.warn('creating CUBLAS context to get version number')
Traceback (most recent call last):
  File "c:\Program Files\Python27\Lib\site-packages\tests\test_fft.py", line 16, in <module>
    import skcuda.fft as fft
  File "c:\Program Files\Python27\lib\site-packages\skcuda\fft.py", line 19, in <module>
    from . import misc
  File "c:\Program Files\Python27\lib\site-packages\skcuda\misc.py", line 29, in <module>
    from . import cula
  File "c:\Program Files\Python27\lib\site-packages\skcuda\cula.py", line 499, in <module>
    _libcula.culaDeviceCungqr.restype = int
  File "c:\Program Files\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "c:\Program Files\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'culaDeviceSorgqr' not found

This is not related to https://github.com/lebedov/scikit-cuda/issues/142 nor to https://github.com/lebedov/scikit-cuda/issues/131 .

Pycuda is working fine, using http://wiki.tiker.net/PyCuda/Examples/Demo . 
Strangely, this issue is not present under python 3.4 or python 3.5.

Thanks for your help

**Comment by gul916** [comment]
Update
This seems to be a specific bug on scikit-cuda 0.5.1 as this bug appears also under python 3.4 and python 3.5 with the proper version. Good news: it disappears using back version 0.5.0:
python -m pip install scikit-cuda==0.5.0
Cheers

**Comment by lebedov** [comment]
SORGQR is only in the standard release of CULA Dense, not the free version. I modified `cula.py` to not raise an exception if the function isn't present. The error didn't occur with 0.5.0 because the SORGQR wrapper wasn't in that version.

**Comment by gul916** [comment]
Ok, thanks for your quick answer and patch.
Cheers
