### ISSUE TITLE
skcuda.linalg.dot() for matrix and 1D vector fails

### ISSUE THREAD

**Issue by DusanNikolov** [lebedov/scikit-cuda#156]
Hi!

I just installed your scikit-cuda, and was trying to run one of the demos (dot_demo.py) when I got this error: Failure: OSError (cublas library not found)

I have the CUDA Toolkit 7.5 installed, and it works, since I'm using CUDA in one of my other projects (C++). Do I need to set an environment variable of some sorts, to tell the scikit where is my cublas.dll?

I tried setting LD_LIBRARY_PATH, but that didn't work.

Also, maybe it's worth mentioning that I am using Python 2.7 32bit version, and cublas.dll in CUDA Toolkit 7.5 only comes in 64bit version.

Thanks in advance for your response,

Regards,
Dusan

**Comment by lebedov** [comment]
Hi, Dušan.

LD_LIBRARY_PATH is Linux-specific and will not have any effect on Windows. Were you able to successfully install/use PyCUDA on your system? I suspect that your 32 bit Python installation isn't finding the 64 bit CUDA libraries. Can you try installing 64 bit Python on your system and using it to install PyCUDA and scikit-cuda?

**Comment by DusanNikolov** [comment]
Hi Lev,

Thanks for the fast reply. I suspected that having 32bit Python might be a
problem... I will try to install 64bit python, and all other packages that
I require and then see if the problem gets resolved. If not, I'll bug you
again if you don't mind.

Thanks again,

Regards,
Dusan

On Wed, Dec 23, 2015 at 8:55 PM, Lev Givon <notifications@github.com> wrote:

> Hi, Dušan.
>
> LD_LIBRARY_PATH is Linux-specific and will not have any effect on Windows.
> Were you able to successfully install/use PyCUDA on your system? I suspect
> that your 32 bit Python installation isn't finding the 64 bit CUDA
> libraries. Can you try installing 64 bit Python on your system and using it
> to install PyCUDA and scikit-cuda?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lebedov/scikit-cuda/issues/156#issuecomment-166979746>
> .
>



-- 
Dušan Nikolov
nikolovdusan92@gmail.com

**Comment by DusanNikolov** [comment]
Hi again,

Just letting you know that installing the 64bit Python fixed the issue I
had before, but since I'm fairly new to Python, I have another question
about the usage of the scikit-cuda...

Do you mind giving me a helping hand with this?

I have the following piece of code:

a_gpu = gpuarray.to_gpu(a[l])
w_gpu = gpuarray.to_gpu(self.weights[l])
temp_gpu = culinalg.dot(w_gpu, a_gpu)
a.append(self.activation(temp_gpu.get()))

# a.append(self.activation(np.dot(a[l], self.weights[l])))

The commented section is the code that I want to replace with cuda piece
above it.
When I tried to do this, and got to the actual execution i got the
following error:

Traceback (most recent call last):
  File "C:/Projects/PyCharm/MLP_CUDA/MLPBackprop with CUBLAS.py", line 147,
in <module>
    main()
  File "C:/Projects/PyCharm/MLP_CUDA/MLPBackprop with CUBLAS.py", line 110,
in main
    nn.fit(xor_in, xor_out, epochs=10000)
  File "C:/Projects/PyCharm/MLP_CUDA/MLPBackprop with CUBLAS.py", line 74,
in fit
    temp_gpu = culinalg.dot(w_gpu, a_gpu)
  File "C:\Python27_64bit\lib\site-packages\skcuda\linalg.py", line 634, in
dot
    return add_dot(x_gpu, y_gpu, out, transa, transb, 1.0, 0.0, handle)
  File "C:\Python27_64bit\lib\site-packages\skcuda\linalg.py", line 461, in
add_dot
    b_f_order = b_gpu.strides[1] > b_gpu.strides[0]
*IndexError: tuple index out of range*

Essentially, it says that it cannot multiply two matrices where one is 3x3
and other 3x1 (this I got while stepping through the code).

I'm sorry if this isn't descriptive enough, but since I'm new to all of
this, please bear with me.

Can you help me fix this, or at least understand why this is occurring?

I can even send you the complete .py file if this code snippet isn't enough.


Thanks a lot for your time and help in advance,

Gratefully,
Dusan.

On Wed, Dec 23, 2015 at 9:49 PM, Dusan Nikolov <nikolovdusan92@gmail.com>
wrote:

> Hi Lev,
>
> Thanks for the fast reply. I suspected that having 32bit Python might be a
> problem... I will try to install 64bit python, and all other packages that
> I require and then see if the problem gets resolved. If not, I'll bug you
> again if you don't mind.
>
> Thanks again,
>
> Regards,
> Dusan
>
> On Wed, Dec 23, 2015 at 8:55 PM, Lev Givon <notifications@github.com>
> wrote:
>
>> Hi, Dušan.
>>
>> LD_LIBRARY_PATH is Linux-specific and will not have any effect on
>> Windows. Were you able to successfully install/use PyCUDA on your system? I
>> suspect that your 32 bit Python installation isn't finding the 64 bit CUDA
>> libraries. Can you try installing 64 bit Python on your system and using it
>> to install PyCUDA and scikit-cuda?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/lebedov/scikit-cuda/issues/156#issuecomment-166979746>
>> .
>>
>
>
>
> --
> Dušan Nikolov
> nikolovdusan92@gmail.com
>



-- 
Dušan Nikolov
nikolovdusan92@gmail.com

**Comment by lebedov** [comment]
Great - I added a note to the installation instructions so that others will hopefully not run into the Python/CUDA architecture mismatch issue.

With regards to your other question, are you sure the shapes of the two operands you are passing to dot() are what you think they are? Try printing the shapes of w_gpu and a_gpu before passing them to dot().

**Comment by DusanNikolov** [comment]
That's a really good idea.

Regarding those shapes, shape of one is (,3) and the other is (3,3). When I
went through the debugging, I saw that func dot (linalg.py) changes the
shape of (,3) to (1,3), and the error occurres when it further goes into
add_dot at the first line from this code block:

a_f_order = a_gpu.strides[1] > a_gpu.strides[0]
b_f_order = b_gpu.strides[1] > b_gpu.strides[0]c_f_order =
c_gpu.strides[1] > c_gpu.strides[0]

That makes sense to me since the first array actually has only one
dimension, so a_gpu.strides[1] does actually goes out of range.
My confusion still remains, on how to manage to do this. Because the
numpy.dot works with the arrays as they are without any problems.

I can send you the complete file, if you have the time to take a look,
but maybe it's better to send you a pm, since all of this goes into
the issue, and it isn't a place for that.


Thanks again for all your help,

Dusan


On Tue, Dec 29, 2015 at 12:24 AM, Lev Givon <notifications@github.com>
wrote:

> Great - I added a note to the installation instructions so that others
> will hopefully not run into the Python/CUDA architecture mismatch issue.
>
> With regards to your other question, are you sure the shapes of the two
> operands you are passing to dot() are what you think they are? Try printing
> the shapes of w_gpu and a_gpu before passing them to dot().
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lebedov/scikit-cuda/issues/156#issuecomment-167677630>
> .
>



-- 
Dušan Nikolov
nikolovdusan92@gmail.com

**Comment by lebedov** [comment]
Seems to be a bug in handling of vectors with only 1 dimension. You can try working around this by ensuring that the 1D vector has 2 dimensions, i.e., (1, 3) or (3, 1) depending on whether it is the first or second operand to dot) before you transfer it to GPU memory.

**Comment by DusanNikolov** [comment]
Oh I think I understand... So what you suggest is that I make the vector 2D
artificially, before transfering?
I'll give that a go and see whether it resolves this issue.

Thanks!

On Tue, Dec 29, 2015 at 4:25 PM, Lev Givon <notifications@github.com> wrote:

> Seems to be a bug in handling of vectors with only 1 dimension. You can
> try working around this by ensuring that the 1D vector has 2 dimensions,
> i.e., (1, 3) or (3, 1) depending on whether it is the first or second
> operand to dot) before you transfer it to GPU memory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lebedov/scikit-cuda/issues/156#issuecomment-167810648>
> .
>



-- 
Dušan Nikolov
nikolovdusan92@gmail.com

**Comment by lebedov** [comment]
Right.

**Comment by lebedov** [comment]
Fixed.
