### ISSUE TITLE
Unnecessary assert in misc.get_by_index()

### ISSUE THREAD

**Issue by ayanc** [lebedov/scikit-cuda#159]
Hi,

The get_by_index() function skcuda.misc has an assert requiring the length of the index vector to be <= length of the array its taking data from. Unless I'm missing something, this seems to be un-necessary, and prevents using the function in many common scenarios: for example, when trying to use get_by_index to do a repmat or im2col type operation, where the same index will appear many times in the index vector, and the output array is expected to be bigger than the input array. 

Ayan

**Comment by lebedov** [comment]
I originally included the check to enforce certain sanity constraints due to the original application in which was using the function, but - as you correctly note - there isn't any fundamental reason to prohibit an index array that is longer than the data array. I removed the check accordingly.
