### ISSUE TITLE
CULA Still Available?

### ISSUE THREAD

**Issue by dtaviation** [lebedov/scikit-cuda#164]
coolatools.com website has problems.  I cannot register.  Do they still exist?  What is the alternative for using linear algebra in skcuda, please?

Thanks

**Comment by nouiz** [comment]
This is the good URL: http://www.culatools.com/

**Comment by lebedov** [comment]
There are some initial bindings for linear algebra functions provided by [MAGMA](http://icl.cs.utk.edu/magma/), but I'm not sure if they work with the latest release of MAGMA and they only cover a subset of the available functions.
