### ISSUE TITLE
culinalg.dot does not work

### ISSUE THREAD

**Issue by mindx0** [lebedov/scikit-cuda#165]
I made two simple 2x2 gpuarray  a and b,   tried to call culinalg.dot(a,b)
it returns unsupported combination of input types

>>> a = gpuarray.to_gpu(np.array([[1,2],[3,4]]))
>>> b = a * 0 + 1
>>> b
array([[1, 1],
       [1, 1]])
>>> type(b)
<class 'pycuda.gpuarray.GPUArray'>
>>> culinalg.dot(a,b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/skcuda/linalg.py", line 634, in dot
    return add_dot(x_gpu, y_gpu, out, transa, transb, 1.0, 0.0, handle)
  File "/usr/local/lib/python3.5/site-packages/skcuda/linalg.py", line 455, in add_dot
    raise ValueError('unsupported combination of input types')
ValueError: unsupported combination of input types
>>> Write failed: Broken pipe

**Comment by lebedov** [comment]
The CUBLAS library used by skcuda.linalg doesn't support multiplication of integer matrices - you will have to convert them to float or double.
