### ISSUE TITLE
Python Alembic Build Error: AttributeError: /tmp/alembicDownload/buildfiletest/source4/alembic-1.5.8/lib/alembicmodule.so: undefined symbol: OArchive

### ISSUE THREAD

**Issue by Jingjung** [lebedov/scikit-cuda#170]
hello

I am new in Alembic I want to build Alembic for Python
finally i have alembicmodule.so but it cannot use
I try this in python
>>> from ctypes import cdll
>>> mydll = cdll.LoadLibrary('/tmp/alembicDownload/buildfiletest/source4/alembic-1.5.8/lib/alembicmodule.so')
>>> oarch = mydll.OArchive('path.../.../file.abc')

so i have error like this
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.6/ctypes/__init__.py", line 366, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python2.6/ctypes/__init__.py", line 371, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /tmp/alembicDownload/buildfiletest/source4/alembic-1.5.8/lib/alembicmodule.so: undefined symbol: OArchive

i check my alembicmodule.so file I try

>>> ldd /tmp/alembicDownload/buildfiletest/pyilmbase/lib/libPyImath.so.2

result show my .so file link to every .so file like this

        linux-vdso.so.1 =>  (0x00007fff767ff000)                                                    
        libPyIex.so.2 => /tmp/alembicDownload/buildfiletest/pyilmbase/lib/libPyIex.so.2 (0x00007f48b51ea000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f48b4fb6000)                                                  
        libImath-2_2.so.12 => /tmp/alembicDownload/buildfiletest/ilmbase/lib/libImath-2_2.so.12 (0x00007f48b4d99000)
        libHalf.so.12 => /tmp/alembicDownload/buildfiletest/ilmbase/lib/libHalf.so.12 (0x00007f48b4b56000)          
        libIexMath-2_2.so.12 => /tmp/alembicDownload/buildfiletest/ilmbase/lib/libIexMath-2_2.so.12 (0x00007f48b4952000)
        libIlmThread-2_2.so.12 => /tmp/alembicDownload/buildfiletest/ilmbase/lib/libIlmThread-2_2.so.12 (0x00007f48b4748000)
        libIex-2_2.so.12 => /tmp/alembicDownload/buildfiletest/ilmbase/lib/libIex-2_2.so.12 (0x00007f48b451d000)            
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f48b4300000)                                                      
        libboost_python.so.1.55.0 => /tmp/alembicDownload/buildfiletest/boost/lib/libboost_python.so.1.55.0 (0x00007f48b40af000)
        libpython2.6.so.1.0 => /usr/lib64/libpython2.6.so.1.0 (0x00007f48b3d08000)                                              
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f48b3a02000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f48b377e000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f48b33e9000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f48b31d3000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003e8f200000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f48b2fcf000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f48b2dcb000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f48b2bc3000)

I use
Alembic 1_05_08
boost 1.55
HDF5 1.8.9
ilmbase 2.2
pyilmbase 2.2

Thank you `:)

**Comment by lebedov** [comment]
I suspect that the symbol you are trying to access via ctypes might not be what you think it is because of [C++ name mangling](https://en.wikipedia.org/wiki/Name_mangling#C.2B.2B). You may wish to post your question on the [Alembic issue tracker](https://github.com/alembic/alembic/issues).

By the way, doesn't Alembic already have [Python bindings](http://docs.alembic.io/#pyalembic)?
