### ISSUE TITLE
Support for CUDA 8.0 - cusolver.py?

### ISSUE THREAD

**Issue by DomagojHack** [lebedov/scikit-cuda#171]
I am failing to run my program that starts with some standard imports.

test.py

```
import pycuda.driver as cuda
import pycuda.autoinit
import pycuda.gpuarray as gpuarray
import pycuda.cumath
from pycuda.compiler import SourceModule
import numpy as np
from skcuda import linalg
linalg.init()
```

Error output:

```
File "test.py", line 10, in <module>
    linalg.init()
  File "/usr/lib/python2.7/site-packages/skcuda/misc.py", line 177, in init
    from . import cusolver
  File "/usr/lib/python2.7/site-packages/skcuda/cusolver.py", line 55, in <module>
    raise OSError('cusolver library not found')
OSError: cusolver library not found
```

All pyCUDA and scikit-CUDA dependencies are installed freshly and all CUDA paths are set up according CUDA documentation.

Cheers

**Comment by DomagojHack** [comment]
Further tinkering got me this nifty error. After running the following:

```
```
import ctypes
tt = ctypes.cdll.LoadLibrary('libcusolver.so.8.0')
```
Traceback (most recent call last):
  File "/home/bioquant/Desktop/Domagoj/dev_CUDA/test2.py", line 3, in <module>
    tt = ctypes.cdll.LoadLibrary('libcusolver.so.8.0')
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 438, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/cuda-8.0/lib64/libcusolver.so.8.0: undefined symbol: GOMP_critical_end
```

**Comment by lebedov** [comment]
Updated to look for CUDA 8.0 libraries.

**Comment by lebedov** [comment]
The second error you observed suggests that you don't have the OpenMP libraries properly installed. If you are on Ubuntu, check whether you have the `libgomp1` package installed. If you do, try running `ldconfig` as root to make sure that the library's path is in the ld.so cache.

**Comment by DomagojHack** [comment]
I am fedora 23 user (as it is officialy supported CUDA 8.0rc OS) with preinstalled `libgomp-5.3.1-6.fc23.x86_64` package. `ldconfig` did nothing. 


Also unrelated to this issue I think there is an typo in `skcuda/cusolver.py` line at line 25

```
    _libcusolver_libname_list = ['libcusolver.so'] + \
                                ['libsolver.so.%s' % v for v in _version_list]
```
Isn't there suposed to be:

```
    _libcusolver_libname_list = ['libcusolver.so'] + \
                                ['libcusolver.so.%s' % v for v in _version_list]
```
like in for example cufft

```
    _libcufft_libname_list = ['libcufft.so'] + \
                             ['libcufft.so.%s' % v for v in _version_list]
```

**Comment by lebedov** [comment]
Correct - just fixed. Thanks!

**Comment by lebedov** [comment]
Not sure what's going on with `libgomp` - you may wish to bring it up on NVIDIA's [developer forum](https://devtalk.nvidia.com/default/board/58/cuda-setup-and-installation/).

**Comment by ibmua** [comment]
I'm experiencing the same issue.

**Comment by lebedov** [comment]
@ibmua: do you mean the libgomp issue? Does it occur with the latest (stable) CUDA 8.0 release?

**Comment by ibmua** [comment]
Okay, so it seems like the latest GitHub version doesn't have that issue while pip one does.

**Comment by lebedov** [comment]
Ah, good. I'll try to get a new release onto pypi next week after I test a few more things with CUDA 8.0.

**Comment by kflansburg** [comment]
Hey, so I was still getting this issue with the latest GitHub version. 

I was able to fix this by explicitly importing the missing library with ctypes before importing cusolver. 

```
ctypes.CDLL('libgomp.so.1', mode=ctypes.RTLD_GLOBAL)
_libcusolver = ctypes.cdll.LoadLibrary(_libcusolver_libname)
```

Perhaps this is still a misconfiguration on my end, but the issue only showed up for Cuda 8.0 for me.

**Comment by aerval** [comment]
I also needed to import libgomp like kflansburg (also with Cuda 8.0), so this seems not to be an exception.

**Comment by lebedov** [comment]
I added @kflansburg's suggested fix to cusolver.py in 55d24de - let me know if there are further problems.

**Comment by DomagojHack** [comment]
@lebedov Just reporting that pypi version still has cusolver problems while Github version works fine.
Cheers
> https://github.com/lebedov/scikit-cuda/issues/171#issuecomment-250994948

**Comment by Mec-iS** [comment]
Same issue with Ubuntu 16.xx and both Python 2.7 and Python 3.5. `libgomp1` is installed. `scikit-cuda` has been installed from PyPi:

```
Traceback (most recent call last):
  File "test2.py", line 8, in <module>
    a = ctypes.cdll.LoadLibrary( "/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcusolver.so" )
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcusolver.so: undefined symbol: GOMP_critical_end
```
@kflansburg solved it

**Comment by lebedov** [comment]
Closing because the issue was fixed in GitHub.

**Comment by jakirkham** [comment]
For some reason `libgomp.so.1` does not work, but `libgomp.so` works for me. Not sure why. Using Ubuntu 16.04.5 LTS with CUDA 9.2.

**Comment by lebedov** [comment]
@jakirkham Not sure why, either - I updated cusolver.py to try loading libgomp.so too just to be safe.

**Comment by jakirkham** [comment]
Thanks :)
