### ISSUE TITLE
misc.sum() fails if x_gpu.ndim > 1 and axis == 1

### ISSUE THREAD

**Issue by Osambezy** [lebedov/scikit-cuda#173]
Commit 5a76f0b introduced the additional keyword argument `order` for the functions `zeros`, `ones` and `inf`.
This breaks the function call in line 1225, where the allocator is passed as a positional argument.

Minimal example that triggers the bug:

```
import skcuda.misc
skcuda.misc.init()
dev = skcuda.misc.init_device()
skcuda.misc.init_context(dev)
a = skcuda.misc.ones((1, 1), 'float64')
b = skcuda.misc.sum(a, axis=1)
```
gives the following error:
```
  File "bug-example.py", line 6, in <module>
    b = skcuda.misc.sum(a, axis=1)
  File "skcuda/misc.py", line 1266, in sum
    return _sum_axis(x_gpu, axis, out=out, keepdims=keepdims)
  File "skcuda/misc.py", line 1225, in _sum_axis
    ons = ones((sum_axis, ), x_gpu.dtype, alloc)
  File "skcuda/misc.py", line 448, in ones
    out = gpuarray.GPUArray(shape, dtype, allocator, order=order)
  File "pycuda/gpuarray.py", line 193, in __init__
    raise ValueError("invalid order: %s" % order)
ValueError: invalid order: <Boost.Python.function object at 0x2629500>
```

In some other calls to these functions throughout scikit-cuda the allocator is passed as a keyword argument.
The solution would be to change line 1225 accordingly and also pass the allocator as a keyword argument like this:
``    ons = ones((sum_axis, ), x_gpu.dtype, allocator=alloc)``

**Comment by lebedov** [comment]
Fixed - thanks!
