### ISSUE TITLE
For loop in cuda

### ISSUE THREAD

**Issue by arita37** [lebedov/scikit-cuda#175]
Hi,

1) Is there a possibility to do a for / while loop in scikit cuda ?

2) What you thnik of mapping numpy namespace like
in CUPY Chainer or Bohrium project ?
http://docs.chainer.org/en/stable/cupy-reference/index.html

**Comment by lebedov** [comment]
1. Well, you can certainly call the skcuda functions from within `for` loops, although there is some additional overhead introduced in the high-level functions that may make it preferable to directly call the low-level wrappers in certain circumstances. What specifically are you trying to do?
2. Do you mean actually provide a numpy-like Python front end to GPU memory, or improve compatibility with chainer/bohrium/etc.? The former is outside of skcuda's primary goal, which is to enable use of GPU-powered scientific computing libraries directly from Python; moreover, there are (as you observed) already several ongoing projects that provide multidimensional GPU array Python interfaces (relatedly, see [this page](https://github.com/inducer/compyte/wiki) as well). Improving compatibility with the latter is potentially within the scope of skcuda, although my own needs and time constraints have led me to focus only on supporting PyCUDA's `GPUArray`.

**Comment by arita37** [comment]
Hello,

I have a function a loop for....
and cannot put it in term of matrix computation.

Want to put the loop for inside Cuda kernel.

Is it possible ?
In that case, is it possible to have a snapshot of code.


Thanks, regards
Kevin









On 02 Sep 2016, at 22:38, "Lev E. Givon" <notifications@github.com> wrote:

Well, you can certainly call the skcuda functions from within for loops, although there is some additional overhead introduced in the high-level functions that may make it preferable to directly call the low-level wrappers in certain circumstances. What specifically are you trying to do?
Do you mean actually provide a numpy-like Python front end to GPU memory, or improve compatibility with chainer/bohrium/etc.? The former is outside of skcuda's primary goal, which is to enable use of GPU-powered scientific computing libraries directly from Python; moreover, there are (as you observed) already several ongoing projects that provide multidimensional GPU array Python interfaces (relatedly, see this page as well). Improving compatibility with the latter is potentially within the scope of skcuda, although my own needs and time constraints have led me to focus only on supporting PyCUDA's GPUArray.
―

**Comment by lebedov** [comment]
CUDA kernels may contain `for` loops, although you do need to put some thought into how to use them to effectively take advantage of the GPU; there are various examples of doing this online (see, e.g., [here](https://wiki.tiker.net/PyCuda/Examples/Mandelbrot) for an example that uses PyCUDA). You may also want to take a look at a book like [CUDA by Example](https://www.amazon.com/dp/0131387685/) or try to find examples of using loops within CUDA kernels on [StackOverflow](http://stackoverflow.com). Relatedly, [this post](http://stackoverflow.com/questions/7024615/putting-a-for-loop-in-a-cuda-kernel) on SO might be helpful.
