### ISSUE TITLE
"cublas libray not found" in win10

### ISSUE THREAD

**Issue by QuantumLiu** [lebedov/scikit-cuda#179]
`>>> from unittest import main, makeSuite, TestCase, TestSuite
>>>
>>> import pycuda.autoinit
>>> import pycuda.gpuarray as gpuarray
>>> import numpy as np
>>>
>>> _SEPS = np.finfo(np.float32).eps
>>> _DEPS = np.finfo(np.float64).eps
>>>
>>> import skcuda.cublas as cublas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\Lib\site-packages\skcuda\cublas.py", line 55, in <module>
    raise OSError('cublas library not found')
OSError: cublas library not found
>>> import skcuda.misc as misc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\Lib\site-packages\skcuda\misc.py", line 25, in <module>
    from . import cublas
  File "C:\Anaconda2\Lib\site-packages\skcuda\cublas.py", line 55, in <module>
    raise OSError('cublas library not found')
OSError: cublas library not found
>>>`

**Comment by QuantumLiu** [comment]
well,i' ve solved this problem.
please add 8.0 version to _version_list in update version,thank you!
`# Load library:
_version_list = [8.0, 7.5, 7.0, 6.5, 6.0, 5.5, 5.0, 4.0]
if 'linux' in sys.platform:
    _libcublas_libname_list = ['libcublas.so'] + \
                              ['libcublas.so.%s' % v for v in _version_list]
elif sys.platform == 'darwin':
    _libcublas_libname_list = ['libcublas.dylib']
elif sys.platform == 'win32':
    if sys.maxsize > 2**32:
        _libcublas_libname_list = ['cublas.dll'] + \
                                  ['cublas64_%s.dll' % int(10*v) for v in _version_list]
    else:
        _libcublas_libname_list = ['cublas.dll'] + \
                                  ['cublas32_%s.dll' % int(10*v) for v in _version_list]
`

**Comment by lebedov** [comment]
Already done - see a5c96a1.
