### ISSUE TITLE
Got Error when runing test_fft

### ISSUE THREAD

**Issue by QuantumLiu** [lebedov/scikit-cuda#180]
ERROR: test_work_area (__main__.test_fft)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_fft.py", line 220, in test_work_area
    plan = fft.Plan(x.shape, np.float32, np.complex64, auto_allocate=False)
TypeError: __init__() got an unexpected keyword argument 'auto_allocate'

----------------------------------------------------------------------
Ran 18 tests in 5.187s

FAILED (errors=1)

**Comment by lebedov** [comment]
Please try the latest code on GitHub.

**Comment by QuantumLiu** [comment]
i copied latest codes to /site-package/skcuda and overwrited them,it worked.
but test_cublasxt still got error:
`C:\Anaconda2\Lib\site-packages\skcuda\cublas.py:282: UserWarning: creating CUBLAS context to get version number
  warnings.warn('creating CUBLAS context to get version number')
EEEE
======================================================================
ERROR: test_cublasXtCgemm (__main__.test_cublasxt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cublasxt.py", line 49, in test_cublasXtCgemm
    cublasxt.cublasXtDeviceSelect(handle, 2, np.array([0, 1], np.int32).ctypes.data)
NameError: global name 'handle' is not defined

======================================================================
ERROR: test_cublasXtDgemm (__main__.test_cublasxt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cublasxt.py", line 37, in test_cublasXtDgemm
    cublasxt.cublasXtDeviceSelect(handle, 2, np.array([0, 1], np.int32).ctypes.data)
NameError: global name 'handle' is not defined

======================================================================
ERROR: test_cublasXtSgemm (__main__.test_cublasxt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cublasxt.py", line 25, in test_cublasXtSgemm
    cublasxt.cublasXtDeviceSelect(handle, 2, np.array([0, 1], np.int32).ctypes.data)
NameError: global name 'handle' is not defined

======================================================================
ERROR: test_cublasXtZgemm (__main__.test_cublasxt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cublasxt.py", line 57, in test_cublasXtZgemm
    a = (np.random.rand(4, 4)+1j*np.random.rand(4, 4)).astype(np.complex256)
AttributeError: 'module' object has no attribute 'complex256'

----------------------------------------------------------------------
Ran 4 tests in 0.000s

FAILED (errors=4)`
