### ISSUE TITLE
cublasXt testing module causing seg fault error

### ISSUE THREAD

**Issue by chmlxj** [lebedov/scikit-cuda#181]
I see following error running the cublasXt test model

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

I can also reproduce this error message with following 3 lines of code:
```

import skcuda.cublasxt as xt
xt_handle = xt.cublasXtCreate()
xt.cublasXtDestroy(xt_handle)
```

**Comment by lebedov** [comment]
I don't observe any segfault when running the create/destroy functions, but a segfault does occur when running the gemm wrappers. What revision of skcuda are you using, by the way?

**Comment by chmlxj** [comment]
I am using version 0.5.2. I also see segfault when running the gemm wrappers.

**Comment by lebedov** [comment]
Someone on [SO](https://stackoverflow.com/questions/47466589) kindly pointed out that some of the argument types for the CUBLASXT functions differ from their CUBLAS equivalents. I updated the bindings accordingly.
