### ISSUE TITLE
cuda 8.0 support

### ISSUE THREAD

**Issue by zeryx** [lebedov/scikit-cuda#185]
Hey guys, so we're using scikit-cuda in a production environment right now (ubuntu 14.04), has worked great for us so far :+1: 

We're in the process of upgrading our infrastructure to cuda 8.0.11; nearly everything works properly.. except scikit-cuda. Here's a runtime exception I got from the latest build:
```
ImportError: libcurand.so.7.5: cannot open shared object file: No such file or directory
```

We have cuda 8.0.11 installed and symlinked properly; every other ML framework is able to play nice with this, however, it seems that scikit-cuda doesn't fully support 8 yet, is this true?

I might be missing something; I'm using the master branch & the latest commit, should I change the setup.py file to integrate the latest cuda commits: https://github.com/lebedov/scikit-cuda/commit/55d24de7080bb9c21ca47cece74a21a9cc5a2ffc,  https://github.com/lebedov/scikit-cuda/commit/5914972df60e851fa86bdee205141110b17898bb and https://github.com/lebedov/scikit-cuda/commit/a5c96a131e560d2e5d25fbe479203a9e869bcd61?

Let me know if any other info is needed for this issue to move forward.

**Comment by lebedov** [comment]
Seems like pycuda on your system was built against CUDA 7.5. Can you rebuild/install it against CUDA 8.0?

**Comment by zeryx** [comment]
Yep that did it perfectly, thanks!
For any future reader running into this same issue, we built a couple of pip wheels to solve this:
https://s3-us-west-2.amazonaws.com/algorithmia-wheels/pycuda-2016.1.2-cp27-none-linux_x86_64.whl
https://s3-us-west-2.amazonaws.com/algorithmia-wheels/scikit_cuda-0.5.2-py2-none-any.whl

Both work perfectly with ubuntu 14.04 and cuda 8.0

**Comment by lebedov** [comment]
Great!
