### ISSUE TITLE
macOS 10.12 & CUDA 8.0 + cudnn 5 – Need setup help!

### ISSUE THREAD

**Issue by subzerofun** [lebedov/scikit-cuda#186]
Hope you can help me – i get a lot of errors during setup, i have just copied the last few lines:

```
75 warnings generated.
ld: warning: directory not found for option '-L/Developer/NVIDIA/CUDA-8.0/lib64'
ld: warning: directory not found for option '-L/Developer/NVIDIA/CUDA-8.0/lib64/stubs'
ld: warning: directory not found for option '-L/Developer/NVIDIA/CUDA-8.0/lib64'
ld: warning: directory not found for option '-L/Developer/NVIDIA/CUDA-8.0/lib64/stubs'
ld: library not found for -lcuda
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: Setup script exited with error: command 'clang++' failed with exit status 1
```

The directories listed with "lib64" are only found on Linux. On OSX/macOS the folders are simply called "lib".

What would i need to change in the makefile and setup.py to successfully install it?

I have already set the env variable "DYLD_LIBRARY_PATH" to "/usr/local/cuda/lib" (all cuda libraries are in there or symlinked to "Developer/NVIDIA/CUDA-8.0/lib"

Don't know if it's relevant, but i get the same errors when i try to install pycuda with "pip2 install scikit-cuda"

Thanks for reading this, i hope there is an easy fix for that!

**Comment by lebedov** [comment]
Before installing scikit-cuda, you may need to build/install pycuda manually and specify where your CUDA files/libraries are located. Try downloading the [latest pycuda tarball from pypi](https://pypi.python.org/pypi/pycuda/2016.1.2), unpack, enter the unpacked directory, and run something like

```
python configure.py --cuda-root=/usr/local/cuda --ldflags="-L/usr/local/cuda/lib"
make
make install
```

**Comment by lebedov** [comment]
Closing - if this is still an issue, feel free to reopen.

**Comment by lebedov** [comment]
Closing - if this is still an issue, feel free to reopen.

**Comment by subzerofun** [comment]
Thanks for asking, these are the results from trying to install pycuda from the link you've provided – with the added config parameters of my cuda folders:

```
11 warnings generated.
clang++ -bundle -undefined dynamic_lookup build/temp.macosx-10.12-x86_64-2.7/src/wrapper/_pvt_struct_v2.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -o build/lib.macosx-10.12-x86_64-2.7/pycuda/_pvt_struct.so 
-L/usr/local/cuda/lib -Xlinker -rpath -Xlinker /usr/local/cuda/lib -Xlinker -rpath 
-Xlinker /usr/local/cuda/lib64 -Xlinker -rpath 
-Xlinker /usr/local/cuda/lib/stubs -Xlinker -rpath -Xlinker /usr/local/cuda/lib64/stubs
```

Damn, there are still entries with the lib64 folders ...

**How can i get rid of the -Xlinker entries with lib64 in it?**

---

**And then the results from reinstalling scikit-cuda with `pip install scikit-cuda`:**
```
   (...)
   75 warnings generated.
   (...)
    ld: warning: directory not found for option '-L/Developer/NVIDIA/CUDA-8.0/lib64'
    ld: warning: directory not found for option '-L/Developer/NVIDIA/CUDA-8.0/lib64/stubs'
    ld: warning: directory not found for option '-L/Developer/NVIDIA/CUDA-8.0/lib64'
    ld: warning: directory not found for option '-L/Developer/NVIDIA/CUDA-8.0/lib64/stubs'
    ld: library not found for -lcuda
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'clang++' failed with exit status 1

    ----------------------------------------
  Rolling back uninstall of pycuda
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-ioqBnJ/pycuda/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-GBGxbq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-ioqBnJ/pycuda/
```

So i guess the problem lies in the pycuda configuration / make and install? 

The directories of your config parameters are correct, i'm using these for other CUDA related projects as well.
`--cuda-root=/usr/local/cuda --ldflags="-L/usr/local/cuda/lib"`

---

### Installation of scikit-cuda, following documentation

The pip install didn't work, so i tried again with the github files. 

Then ran the test of the documentation: `python setup.py test`

Results:
```
running test
running egg_info
writing requirements to scikit_cuda.egg-info/requires.txt
writing scikit_cuda.egg-info/PKG-INFO
writing namespace_packages to scikit_cuda.egg-info/namespace_packages.txt
writing top-level names to scikit_cuda.egg-info/top_level.txt
writing dependency_links to scikit_cuda.egg-info/dependency_links.txt
reading manifest file 'scikit_cuda.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'scikit_cuda.egg-info/SOURCES.txt'
running build_ext
test_cublasCaxpy (test_cublas.test_cublas) ... ok
test_cublasCcopy (test_cublas.test_cublas) ... ok
test_cublasCdotc (test_cublas.test_cublas) ... ok
test_cublasCdotu (test_cublas.test_cublas) ... ok
test_cublasCgeam (test_cublas.test_cublas) ... ok
test_cublasCgemmBatched (test_cublas.test_cublas) ... ok
test_cublasCgemv (test_cublas.test_cublas) ... ok
test_cublasCscal (test_cublas.test_cublas) ... ok
test_cublasCsscal (test_cublas.test_cublas) ... ok
test_cublasCswap (test_cublas.test_cublas) ... ok
test_cublasDasum (test_cublas.test_cublas) ... ok
test_cublasDaxpy (test_cublas.test_cublas) ... ok
test_cublasDcopy (test_cublas.test_cublas) ... ok
test_cublasDdot (test_cublas.test_cublas) ... ok
test_cublasDgeam (test_cublas.test_cublas) ... ok
test_cublasDgemmBatched (test_cublas.test_cublas) ... ok
test_cublasDgemv (test_cublas.test_cublas) ... ok
test_cublasDgetrfBatched (test_cublas.test_cublas) ... ok
test_cublasDrnm2 (test_cublas.test_cublas) ... ok
test_cublasDscal (test_cublas.test_cublas) ... ok
test_cublasDswap (test_cublas.test_cublas) ... ok
test_cublasDtrsmBatched (test_cublas.test_cublas) ... ok
test_cublasDzasum (test_cublas.test_cublas) ... ok
test_cublasDzrnm2 (test_cublas.test_cublas) ... ok
test_cublasIcamax (test_cublas.test_cublas) ... ok
test_cublasIcamin (test_cublas.test_cublas) ... ok
test_cublasIdamax (test_cublas.test_cublas) ... ok
test_cublasIdamin (test_cublas.test_cublas) ... ok
test_cublasIsamax (test_cublas.test_cublas) ... ok
test_cublasIsamin (test_cublas.test_cublas) ... ok
test_cublasIzamax (test_cublas.test_cublas) ... ok
test_cublasIzamin (test_cublas.test_cublas) ... ok
test_cublasSasum (test_cublas.test_cublas) ... ok
test_cublasSaxpy (test_cublas.test_cublas) ... ok
test_cublasScasum (test_cublas.test_cublas) ... ok
test_cublasScopy (test_cublas.test_cublas) ... ok
test_cublasScrnm2 (test_cublas.test_cublas) ... ok
test_cublasSdot (test_cublas.test_cublas) ... ok
test_cublasSgeam (test_cublas.test_cublas) ... ok
test_cublasSgemmBatched (test_cublas.test_cublas) ... ok
test_cublasSgemv (test_cublas.test_cublas) ... ok
test_cublasSgetrfBatched (test_cublas.test_cublas) ... ok
test_cublasSrnm2 (test_cublas.test_cublas) ... ok
test_cublasSrot (test_cublas.test_cublas) ... ok
test_cublasSscal (test_cublas.test_cublas) ... ok
test_cublasSswap (test_cublas.test_cublas) ... ok
test_cublasStrsmBatched (test_cublas.test_cublas) ... ok
test_cublasZaxpy (test_cublas.test_cublas) ... ok
test_cublasZcopy (test_cublas.test_cublas) ... ok
test_cublasZdotc (test_cublas.test_cublas) ... ok
test_cublasZdotu (test_cublas.test_cublas) ... ok
test_cublasZdscal (test_cublas.test_cublas) ... ok
test_cublasZgeam (test_cublas.test_cublas) ... ok
test_cublasZgemmBatched (test_cublas.test_cublas) ... ok
test_cublasZgemv (test_cublas.test_cublas) ... ok
test_cublasZscal (test_cublas.test_cublas) ... ok
test_cublasZswap (test_cublas.test_cublas) ... ok
test_cublasXtCgemm (test_cublasxt.test_cublasxt) ... Segmentation fault: 11
```

It crashed ... hooray!  🎉

Hope you are still in the mood of helping – i can't figure out the solution to get both pycuda and scikit-cuda to work ... The first thing that i need to get an error-free install of pycuda – right?

Are there any setup parameters missing – something OSX specific?

---

### setup.py – pycuda

Is there anything missing here for the OSX folder paths?
```python
    lib64 = "lib64"
    import sys
    if sys.platform.startswith("win"):
        # https://github.com/inducer/pycuda/issues/113
        lib64 = "lib/x64"

        cxxflags_default.extend(['/EHsc'])
        ldflags_default.extend(['/FORCE'])

    default_lib_dirs = [
        "${CUDA_ROOT}/lib",
        "${CUDA_ROOT}/"+lib64,
        # https://github.com/inducer/pycuda/issues/98
        "${CUDA_ROOT}/lib/stubs",
        "${CUDA_ROOT}/%s/stubs" % lib64,
        ]
```

### siteconf.py – pycuda

This also looks wrong ... Why are there still these lib64 entries?

```
BOOST_INC_DIR = []
BOOST_LIB_DIR = []
BOOST_COMPILER = 'gcc43'
USE_SHIPPED_BOOST = True
BOOST_PYTHON_LIBNAME = ['boost_python-py27']
BOOST_THREAD_LIBNAME = ['boost_thread']
CUDA_TRACE = False
CUDA_ROOT = '/usr/local/cuda'
CUDA_ENABLE_GL = False
CUDA_ENABLE_CURAND = True
CUDADRV_LIB_DIR = ['${CUDA_ROOT}/lib', '${CUDA_ROOT}/lib64', '${CUDA_ROOT}/lib/stubs', '${CUDA_ROOT}/lib64/stubs']
CUDADRV_LIBNAME = ['cuda']
CUDART_LIB_DIR = ['${CUDA_ROOT}/lib', '${CUDA_ROOT}/lib64', '${CUDA_ROOT}/lib/stubs', '${CUDA_ROOT}/lib64/stubs']
CUDART_LIBNAME = ['cudart']
CURAND_LIB_DIR = ['${CUDA_ROOT}/lib', '${CUDA_ROOT}/lib64', '${CUDA_ROOT}/lib/stubs', '${CUDA_ROOT}/lib64/stubs']
CURAND_LIBNAME = ['curand']
CXXFLAGS = []
LDFLAGS = ['-L/usr/local/cuda/lib']
```

**Comment by subzerofun** [comment]
I have edited the siteconf.py for pycuda (changed lib64 to lib) and installed it again – this time i got no warnings.

And then i tried scikit-cuda again from source. 

These are the results of the tests:
```
python test_cublas.py
........................................................
----------------------------------------------------------------------
Ran 56 tests in 0.753s
OK



python test_cublasxt.py
Segmentation fault: 11



python test_fft.py
..................
----------------------------------------------------------------------
Ran 18 tests in 0.631s
OK



python test_integrate.py
........
----------------------------------------------------------------------
Ran 8 tests in 1.008s
OK



python test_linalg.py
(a lot of errors...)
(...)
NotImplementedError: CULA not installed
----------------------------------------------------------------------
Ran 149 tests in 4.205s
FAILED (errors=50)



python test_misc.py
.../usr/local/lib/python2.7/site-packages/pycuda-2016.1.2-py2.7-macosx-10.12-x86_64.egg/pycuda/scan.py:373: UserWarning: The CUDA compiler succeeded, but said the following:
kernel.cu(273): warning: __shared__ memory variable with non-empty constructor or destructor (potential race between threads)
  scan_intervals_src, options=options, no_extern_c=True)
.............................................
----------------------------------------------------------------------
Ran 48 tests in 53.336s
OK



python test_rlinalg.py
NotImplementedError: CULA not installed
----------------------------------------------------------------------
Ran 32 tests in 0.459s
FAILED (errors=32)



python test_special.py
......
----------------------------------------------------------------------
Ran 6 tests in 5.685s
OK
```

So 2 FAILED because of the missing CULA install – **do i need CULA?** Their site is unfortunately experiencing issues (no working downloads)

And the test_cublasxt.py didn't even output anything.

So only some functions of scikit-cuda are working now. That's not ideal if i want to try out a github project that need to import the scikit-cuda functions...

Hope i'm not spamming this thread with too much info...

**Comment by lebedov** [comment]
CULA is required for certain functions. As you have observed, it no longer is freely available; I've been gradually adding support for other libraries (CUSOLVER, MAGMA) that provide alternate functionality with the eventual aim of deprecating CULA support.

For future reference, pycuda installation issues are best discussed on the [pycuda mailing list](https://wiki.tiker.net/PyCuda/MailingList).

**Comment by subzerofun** [comment]
Thanks for the info... I've subscribed to the mailing list right now.

Is there are documentation or guide on how to replace CULA with CUSOLVER or MAGMA?

### MAGMA

I found two sites for MAGMA:

**1) http://magma.maths.usyd.edu.au/magma/**

The full version is not free – there is only a student version. But since i'm not a student i guess it's useless to contact them for the install files.

**2) http://icl.cs.utk.edu/magma/**

Install guide:
http://icl.cs.utk.edu/projectsfiles/magma/doxygen/installing.html

Can i use the second one or is there a MAGMA github repo you would rather recommend?

---
### CUSOLVER

I assume CUSOLVER is part of the Nvidia CUDA devkit. So i already have the needed files in /usr/local/cuda ?

**Sorry to bother you again... but how can i get pycuda / skicit-cuda to use CUSOLVER or MAGMA instead of CULA?**

**What would be the better choice and easier to install for OSX?**

**Comment by lebedov** [comment]
I was referring to the MAGMA package from UTK. Unfortunately, you will have to compile it yourself; I'm not aware of any precompiled packages for MacOS, and I don't have a Mac with an NVIDIA GPU on which I can test MAGMA.

As you observed, CUSOLVER is already included with your CUDA installation. Some of the high-level skcuda functions in the latest revision on Github have already been updated to permit the use of CUSOLVER; you just need to pass those functions the named parameter lib='cusolver' (see, e.g., linalg.svd()). What function(s) are you specifically interested in using?

**Comment by guillochon** [comment]
So I'll make a request here for `cho_solve` to be implemented in CUSOLVER. Also, it would be nice to have an equivalent of `cholesky` available as well.

**Comment by lebedov** [comment]
@guillochon, can you please open a new issue containing the CUSOLVER-backed cho_solve/cholesky request? Thanks!

**Comment by guillochon** [comment]
Done: https://github.com/lebedov/scikit-cuda/issues/198
