### ISSUE TITLE
CUDA driver library on OSX not found

### ISSUE THREAD

**Issue by kambysese** [lebedov/scikit-cuda#187]
@lebedov thought I re-try my luck with CUDA 7.5 install on OSX 10.11.6. I am still encountering errors reminiscent of #157. `nosetests` returned 8 OSErrors (CUDA driver library not found) as did `dot_demo.py`

> Traceback (most recent call last):
  File "dot_demo.py", line 13, in <module>
    import skcuda.linalg as culinalg
  File "/Users/ktavabi/Projects/scikit-cuda/skcuda/linalg.py", line 23, in <module>
    from . import cublas
  File "/Users/ktavabi/Projects/scikit-cuda/skcuda/cublas.py", line 22, in <module>
    from . import cuda
  File "/Users/ktavabi/Projects/scikit-cuda/skcuda/cuda.py", line 10, in <module>
    from .cudadrv import *
  File "/Users/ktavabi/Projects/scikit-cuda/skcuda/cudadrv.py", line 32, in <module>
    raise OSError('CUDA driver library not found')
OSError: CUDA driver library not found

`nvcc` returns
>NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Thu_Sep_24_00:26:39_CDT_2015
Cuda compilation tools, release 7.5, V7.5.19

And PyCuda 2016.1.2 is properly installed. The TB is not the same as in #157 but I am not sure I'm not dealing with a PATH/environment issue?

**Comment by lebedov** [comment]
Can you try the latest revision in the fix_osx_find_lib_path branch? Added another fix that might address the problem.

**Comment by kambysese** [comment]
@lebedov thanks for response. It turned out installing CUDA 8 using homebrew in combination with command line tools v 8.2, and careful make of pycuda this issue was resolved in the master scikits-cuda branch. Alas the whopping 200mb of GPU bandwidth I managed to recover turned out to make my laptop more unstable. Sorry for the inconvenience.
