### ISSUE TITLE
Correct way to call cusolver linear solver (How to pass the transpose flag?)

### ISSUE THREAD

**Issue by botev** [lebedov/scikit-cuda#191]
I'm trying to use the `skcuda.cusolver.cusolverDnSgetrs` for solving a linear system, however at the moment I get the error:
```bash
Traceback (most recent call last):
  File "solver.py", line 55, in <module>
    devInfo=devInfo_gpu.ptr
  File "/share/apps/barber/system/lib/python3.6/site-packages/scikit_cuda-0.5.2-py3.6.egg/skcuda/cusolver.py", line 640, in cusolverDnSgetrs
    ldb, int(devInfo))
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```
My guess, that I did not manage to figure out how to pass correclty the tranpose flag, which corresponds to `cublasOperation_t`. Currenlty, I've tried with `'N'`, `'n'`, `'N'.encode('ascii')`, `'n'.encode('ascii')` and non of those works. The test code is:
```python
import pycuda.autoinit
import pycuda.driver as drv
import pycuda.gpuarray as gpuarray
import numpy as np

import ctypes

from skcuda import cusolver
import scipy.linalg

rows = 20
cols = 10

a = np.random.random((rows, rows)).astype("float32")
a = np.dot(a, a.T)
b = np.random.random((rows, cols)).astype("float32")
solved = c = scipy.linalg.solve(a, b)

a_gpu = gpuarray.to_gpu(a.copy())
b_gpu = gpuarray.to_gpu(b.copy())

devInfo = gpuarray.zeros(1, np.int32)
devIpiv = gpuarray.zeros((rows, ), np.int32)
handle = cusolver.cusolverDnCreate()

worksize = cusolver.cusolverDnSgetrf_bufferSize(handle, rows, rows, a_gpu.ptr, 0)
print("LU worksize:", worksize)

Workspace = gpuarray.empty(worksize, np.float32)

lu_status = cusolver.cusolverDnSgetrf(
    handle=handle,
    m=rows,
    n=rows,
    A=a_gpu.ptr,
    lda=rows,
    Workspace=Workspace.ptr,
    devIpiv=devIpiv.ptr,
    devInfo=devInfo.ptr
)
print(lu_status, devInfo)

solve_status = cusolver.cusolverDnSgetrs(
    handle=handle,
    trans="n",
    n=rows,
    nrhs=cols,
    A=a_gpu.ptr,
    lda=rows,
    devIpiv=devIpiv.ptr,
    B=b_gpu.ptr,
    ldb=rows,
    devInfo=devInfo.ptr
)

print(solve_satus, devInfo)

status = cusolver.cusolverDnDestroy(handle)
```
So far I did not find any examples or documentation of how to achieve this correctly.

**Comment by lebedov** [comment]
In the latest releases of CUDA, the transposition parameters are specified using an enum rather than a char; however, I map the latter to the former to support the old usage. I hadn't done so for the getrs wrappers, however - I just fixed this.

**Comment by lebedov** [comment]
Let me know if you encounter further problems - if not, feel free to close this issue.

**Comment by botev** [comment]
Ah, great, however, I did not find the `ascii encoding to work, as you mention they are an enums, but are mapped to integers. Thus, at least on my system, to work I used `skcuda.cublas._CUBLAS_OP[trans]`.

**Comment by lebedov** [comment]
Did you try the [latest revision](https://github.com/lebedov/scikit-cuda/commit/312d83900f8e362a67d1c3b04b95333027a1b9a9) I just checked in?

**Comment by lebedov** [comment]
Strange - I evidently didn't check in the conversion from string to int via _CUBLAS_OP. Fixed.
