### ISSUE TITLE
incorrect calculation?

### ISSUE THREAD

**Issue by papaloizouc** [lebedov/scikit-cuda#195]
hi been using the dot_demo seems there's some inaccuracies in compared to numpy on bigger arrays, it seems to be consistently wrong?

[[  **146.34289551** -1163.25415039   -14.09494019 -1067.37756348]
 [  -16.50552368   264.65948486  -572.22631836    28.61650085]]
[[  **146.34268188** -1163.25390625   -14.09505177 -1067.37756348]
 [  -16.50546455   264.65963745  -572.22637939    28.61683273]]
Success status:  False
[[  **146.34289551** -1163.25415039   -14.09494019 -1067.37756348]
 [  -16.50552368   264.65948486  -572.22631836    28.61650085]]
[[  **146.34268188** -1163.25390625   -14.09505177 -1067.37756348]
 [  -16.50546455   264.65963745  -572.22637939    28.61683273]]

```
#!/usr/bin/env python

from __future__ import print_function

import pycuda.autoinit
import pycuda.gpuarray as gpuarray
import pycuda.driver as drv
import numpy as np

import skcuda.linalg as culinalg
import skcuda.misc as cumisc
culinalg.init()

import string
demo_types = [np.float32]

for t in demo_types:
    print('Testing matrix multiplication for type ' + str(np.dtype(t)))

    a = np.asarray(np.random.normal(size=(1000, 500)), dtype=t)
    b = np.asarray(np.random.normal(size=(500, 500)), dtype=t)
    c = np.asarray(np.random.normal(size=(500, 500)), dtype=t)

    a_gpu = gpuarray.to_gpu(a)
    b_gpu = gpuarray.to_gpu(b)
    c_gpu = gpuarray.to_gpu(c)

    temp_gpu = culinalg.dot(a_gpu, b_gpu)
    d_gpu = culinalg.dot(temp_gpu, c_gpu)
    temp_gpu.gpudata.free()
    del(temp_gpu)

    result =  d_gpu.get()
    r = np.dot(np.dot(a, b), c)
    print(r[:2,:4])
    print(result[:2,:4])
    print('Success status: ', np.allclose(r, result))


    a_gpu = gpuarray.to_gpu(a)
    b_gpu = gpuarray.to_gpu(b)
    c_gpu = gpuarray.to_gpu(c)

    temp_gpu = culinalg.dot(a_gpu, b_gpu)
    d_gpu = culinalg.dot(temp_gpu, c_gpu)
    temp_gpu.gpudata.free()
    del(temp_gpu)

    result =  d_gpu.get()
    r = np.dot(np.dot(a, b), c)
    print(r[:2,:4])
    print(result[:2,:4])

    print('Success status: ', np.allclose(r, result))

```

**Comment by lebedov** [comment]
Differences in matrix multiplication implementations (i.e., NVIDIA's CUBLAS and whatever BLAS libraries your numpy installation was built against) are more pronounced for large single precision (float32) matrices. If you need the results to match those of numpy, use double precision.
