### ISSUE TITLE
Equivalent of scipy.cholesky for linalg

### ISSUE THREAD

**Issue by guillochon** [lebedov/scikit-cuda#199]
Right now we only have `cho_factor` available within `linalg`, but there are reasons to use the slightly more expensive `cholesky` calculation (for instance, if you need the determinant of the matrix as well). It would be great to have it available.

**Comment by lebedov** [comment]
The only difference in [current implementations](https://github.com/scipy/scipy/blob/master/scipy/linalg/decomp_cholesky.py) of `scipy.cholesky` and `scipy.cho_factor` that I can see is that the latter returns a flag indicating whether the factor is in the lower or upper triangle. Is that the additional functionality you want? If not, was it in an earlier release of scipy?

**Comment by guillochon** [comment]
@lebedov There's another difference, the matrix returned by `cho_factor` contains random entries:

```
    .. warning::
        The returned matrix also contains random data in the entries not
        used by the Cholesky decomposition. If you need to zero these
        entries, use the function `cholesky` instead.
```

...whereas `cholesky` does not. This means you can take the determinant of `cholesky`'s output and retrieve the same value as the original matrix, this is not true of `cho_factor`.

**Comment by lebedov** [comment]
Done.
