### ISSUE TITLE
cublas library not found

### ISSUE THREAD

**Issue by joseph-valles** [lebedov/scikit-cuda#202]
Hi, I'm using Cuda Toolkit v8.0 with Anaconda3 on Windows 10 and similar to #156 importing skcuda.linalg raises `OSError: cublas library not found`. However, my Python is 64-bit.
`Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32`

I reinstalled Cuda Toolkit, PyCuda and scikit-cuda but I get the same error. Do I need to include something in my Path?

**Comment by joseph-valles** [comment]
The issue is in cublas.py; _libcublas_libname_list is `['cublas.dll', 'cublas64_75.dll', 'cublas64_70.dll', 'cublas64_65.dll', 'cublas64_60.dll', 'cublas64_55.dll', 'cublas64_50.dll', 'cublas64_40.dll']`, but my cublas is named cublas64_80.dll.

**Comment by lebedov** [comment]
This was fixed in #171 - please try the latest revision on GitHub.

**Comment by vhcg77** [comment]
Hi. now I am using Cuda Toolkit v9.0 with anaconda on Windows 10 and I am getting this error:

import skcuda.linalg as linalg
Traceback (most recent call last):

  File "<ipython-input-6-beeb4b10a4dd>", line 1, in <module>
    import skcuda.linalg as linalg

  File "C:\Users\victo\Anaconda3\envs\spikesorting_tsne\lib\site-packages\skcuda\linalg.py", line 21, in <module>
    from . import cublas

  File "C:\Users\victo\Anaconda3\envs\spikesorting_tsne\lib\site-packages\skcuda\cublas.py", line 55, in <module>
    raise OSError('cublas library not found')

OSError: cublas library not found

My python version is 3.6.6

**Comment by lebedov** [comment]
@vhcg77 Are you using the latest revision from GitHub? In the future, please open a separate issue rather than appending to a closed issue.

**Comment by vhcg77** [comment]
Hi! Sorry, I appended here because, the issue was very similar. I will open a new issue. Thanks!

**Comment by cegprakash** [comment]
I face the same issue with scikit-cuda==0.5.2 + Windows 10 + Nvdia Cuda compiler V10.0.130

Can we reopen this?

**Comment by lebedov** [comment]
@cegprakash It's fine to reference old issues, but (as I noted in earlier in this issue), please use the new issue for communication about whatever problem you are encountering.
