### ISSUE TITLE
misc.divide problem

### ISSUE THREAD

**Issue by schlepil** [lebedov/scikit-cuda#206]
Hello everyone,

Is there a problem with misc.divide? When trying to use it like
c = misc.divide(a,b) with a=[n,m] and b=[1,m] I get

  File "/usr/local/lib/python3.4/dist-packages/skcuda/misc.py", line 1084, in divide
    return binaryop_2d("/", operator.div, False, x_gpu, y_gpu)
AttributeError: 'module' object has no attribute 'div'

is it possible that the line

return binaryop_2d("/", operator.div, False, x_gpu, y_gpu)

should read

return binaryop_2d("/", operator.**true**div, False, x_gpu, y_gpu)

At least the result seem correct with this line comparing to numpy.

Best regards!

**Comment by lebedov** [comment]
This was fixed in the master branch a while ago.
