### ISSUE TITLE
Value 'sm_21' is not defined for option 'gpu-architecture'

### ISSUE THREAD

**Issue by supremefist** [lebedov/scikit-cuda#225]
Hi,

I am using the development branch of scikit-cuda (0.5.2) on ubuntu 14.04 with python 2.7.13. I have cuda 9.0 and NVidia driver 384.81. The cuda deviceQuery sample gives the following output:

> ./deviceQuery Starting...
> 
>  CUDA Device Query (Runtime API) version (CUDART static linking)
> 
> Detected 1 CUDA Capable device(s)
> 
> Device 0: "GeForce GT 730"
>   CUDA Driver Version / Runtime Version          9.0 / 9.0
>   CUDA Capability Major/Minor version number:    2.1
>   Total amount of global memory:                 1985 MBytes (2081619968 bytes)
> MapSMtoCores for SM 2.1 is undefined.  Default to use 64 Cores/SM
> MapSMtoCores for SM 2.1 is undefined.  Default to use 64 Cores/SM
>   ( 2) Multiprocessors, ( 64) CUDA Cores/MP:     128 CUDA Cores
>   GPU Max Clock rate:                            1400 MHz (1.40 GHz)
>   Memory Clock rate:                             800 Mhz
>   Memory Bus Width:                              128-bit
>   L2 Cache Size:                                 131072 bytes
>   Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65535), 3D=(2048, 2048, 2048)
>   Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
>   Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
>   Total amount of constant memory:               65536 bytes
>   Total amount of shared memory per block:       49152 bytes
>   Total number of registers available per block: 32768
>   Warp size:                                     32
>   Maximum number of threads per multiprocessor:  1536
>   Maximum number of threads per block:           1024
>   Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
>   Max dimension size of a grid size    (x,y,z): (65535, 65535, 65535)
>   Maximum memory pitch:                          2147483647 bytes
>   Texture alignment:                             512 bytes
>   Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
>   Run time limit on kernels:                     No
>   Integrated GPU sharing Host Memory:            No
>   Support host page-locked memory mapping:       Yes
>   Alignment requirement for Surfaces:            Yes
>   Device has ECC support:                        Disabled
>   Device supports Unified Addressing (UVA):      Yes
>   Supports Cooperative Kernel Launch:            No
>   Supports MultiDevice Co-op Kernel Launch:      No
>   Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
>   Compute Mode:
>      < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
> 
> deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.0, CUDA Runtime Version = 9.0, NumDevs = 1
> Result = PASS

I am trying to run one of the scikit-cuda examples and have the following code:

```
import pycuda.autoinit
import pycuda.gpuarray as gpuarray
import numpy as np
import skcuda
import skcuda.linalg as linalg
linalg.init()
x = np.asarray(np.random.rand(4, 4), np.float32)
y = np.asarray(np.random.rand(4, 4), np.float32)
x_gpu = gpuarray.to_gpu(x)
y_gpu = gpuarray.to_gpu(y)
z_gpu = linalg.multiply(x_gpu, y_gpu)
np.allclose(x*y, z_gpu.get())

```

When I run it, I get the following error:

> Traceback (most recent call last):
>   File "cuda_demo.py", line 11, in <module>
>     z_gpu = linalg.multiply(x_gpu, y_gpu)
>   File "/home/trader/miniconda/envs/empiric/lib/python2.7/site-packages/scikit_cuda-0.5.2-py2.7.egg/skcuda/linalg.py", line 2034, in multiply
>     func(x_gpu, y_gpu, z_gpu)
>   File "/home/trader/miniconda/envs/empiric/lib/python2.7/site-packages/pycuda/elementwise.py", line 199, in __call__
>     range_ is not None or slice_ is not None)
>   File "/home/trader/miniconda/envs/empiric/lib/python2.7/site-packages/pytools/__init__.py", line 578, in wrapper
>     result = function(obj, *args, **kwargs)
>   File "/home/trader/miniconda/envs/empiric/lib/python2.7/site-packages/pycuda/elementwise.py", line 177, in generate_stride_kernel_and_types
>     **self.gen_kwargs)
>   File "/home/trader/miniconda/envs/empiric/lib/python2.7/site-packages/pycuda/elementwise.py", line 147, in get_elwise_kernel_and_types
>     keep, options, **kwargs)
>   File "/home/trader/miniconda/envs/empiric/lib/python2.7/site-packages/pycuda/elementwise.py", line 75, in get_elwise_module
>     options=options, keep=keep)
>   File "/home/trader/miniconda/envs/empiric/lib/python2.7/site-packages/pycuda/compiler.py", line 291, in __init__
>     arch, code, cache_dir, include_dirs)
>   File "/home/trader/miniconda/envs/empiric/lib/python2.7/site-packages/pycuda/compiler.py", line 255, in compile
>     return compile_plain(source, options, keep, nvcc, cache_dir, target)
>   File "/home/trader/miniconda/envs/empiric/lib/python2.7/site-packages/pycuda/compiler.py", line 78, in compile_plain
>     checksum.update(preprocess_source(source, options, nvcc).encode("utf-8"))
>   File "/home/trader/miniconda/envs/empiric/lib/python2.7/site-packages/pycuda/compiler.py", line 55, in preprocess_source
>     cmdline, stderr=stderr)
> pycuda.driver.CompileError: nvcc preprocessing of /tmp/tmpNaUO17.cu failed
> [command: nvcc --preprocess -arch sm_21 -I/home/trader/miniconda/envs/empiric/lib/python2.7/site-packages/pycuda/cuda /tmp/tmpNaUO17.cu --compiler-options -P]
> [stderr:
> nvcc fatal   : Value 'sm_21' is not defined for option 'gpu-architecture'
> ]

Is compute capability 2.1 too low for the functionality I am trying to make use of? Do you have any other ideas what might be wrong?

Thanks in advance,
Riaan

**Comment by nouiz** [comment]
Your driver is too recent for your GPU. Upgrade your GPU or use an older
driver.

**Comment by supremefist** [comment]
Thank you very much! I will!
