### ISSUE TITLE
linalg.dot: unsupported combination of input order

### ISSUE THREAD

**Issue by ncioj10** [lebedov/scikit-cuda#232]
Hi,
I've encountered a problem with linalg.dot. When I take two numpy arrays convert them to gpu arrays and try to calculate the dot product I always receive an error (it works with the samples provided in the docs though). Where does this error come from?

The code:
```
def setup():

x = np.random.randn(10, 2, 3).astype(np.float32)
w = np.random.randn(6, 5).astype(np.float32)
b = np.random.randn(5).astype(np.float32)
dout = np.random.randn(10, 5).astype(np.float32)

dx_num = eval_numerical_gradient_array(lambda x: affine_forward(x, w, b)[0], x, dout)
dw_num = eval_numerical_gradient_array(lambda w: affine_forward(x, w, b)[0], w, dout)
db_num = eval_numerical_gradient_array(lambda b: affine_forward(x, w, b)[0], b, dout)

_, cache = affine_forward(x, w, b)
dx, dw, db = affine_backward(dout, cache)

def calculate(x,w):

   linalg.init()
   reshaped_input = x.reshape(x.shape[0], -1)
    dout_gpu = gpuarray.to_gpu(np.asarray(dout,np.float32))
    w_gpu = gpuarray.to_gpu(np.asarray(w,np.float32)).transpose()
    dx_gpu = linalg.dot(dout_gpu,w_gpu )


```

The error:
```

in affine_backward(dout, cache)
     71     print(dout_gpu.dtype)
     72 
---> 73     dx_gpu = linalg.dot(dout_gpu,w_gpu )
     74     #np.allclose(np.dot(a, b), c_gpu.get())
     75     dx = np.dot(dout,w.T)

/anaconda3/lib/python3.6/site-packages/scikit_cuda-0.5.2-py3.6.egg/skcuda/linalg.py in dot(x_gpu, y_gpu, transa, transb, handle, out)
   1056                 out = gpuarray.empty((m, n), x_gpu.dtype, order="C", allocator=alloc)
   1057 
-> 1058     add_dot(x_gpu, y_gpu, out, transa, transb, 1.0, 0.0, handle)
   1059     if 'out_shape' in locals():
   1060         return out.reshape(out_shape)

/anaconda3/lib/python3.6/site-packages/scikit_cuda-0.5.2-py3.6.egg/skcuda/linalg.py in add_dot(a_gpu, b_gpu, c_gpu, transa, transb, alpha, beta, handle)
    878 
    879     if a_f_order != b_f_order:
--> 880         raise ValueError('unsupported combination of input order')
    881     if a_f_order != c_f_order:
    882         raise ValueError('invalid order for c_gpu')

ValueError: unsupported combination of input order`

    linalg.init()
    reshaped_input = x.reshape(x.shape[0], -1)
    dout_gpu = gpuarray.to_gpu(np.asarray(dout,np.float32))
    w_gpu = gpuarray.to_gpu(np.asarray(w,np.float32)).transpose()

```

I am using newest scikit cuda built from master, Cuda9, CUDNN7, Anaconda and Python 3.6 as environment and a Jupyter Notebook.

**Comment by nmerrill67** [comment]
`
    w_gpu = gpuarray.to_gpu(np.asarray(w,np.float32)).transpose()
`
This is where I believe your mistake is. The transposing is done inside linalg.dot. When you call transpose() it simply changes the array  from a C order to F order, hence your mismatching ordering error. Take out the `.transpose()` and you should be fine.

**Comment by lebedov** [comment]
@nmerrill67 is correct. Note also that `skcuda.linalg.dot` lets one specify whether an argument should be treated as transposed without having to explicitly transpose the argument, i.e.,

    dout_gpu = gpuarray.to_gpu(dout)
    w_gpu = gpuarray.to_gpu(w)
    dx_gpu = linalg.dot(dout_gpu, w_gpu, 'N', 'T')

**Comment by ncioj10** [comment]
Thank you very much this indeed solved my problem! The proposal by @lebedov looks very clean and concise!

**Comment by pgabi** [comment]
@lebedov, but say I have two matrices a and b each of size 4x4, and say somewhere along my program I transposed matrix b. At a later stage, I need to multiply these two matrices. Mathematically, the multiplication is defined, and can be done using numpy, but linalg.dot will fail since the strides are not compatible. What is the right way to handle such cases?

**Comment by lebedov** [comment]
@pgabi, if by "transpose" you mean call `b.transpose()`, why not just pass the original `b` to `linalg.dot(a, b, 'N', 'T')`?
