### ISSUE TITLE
Support for CUDA 9.0 - cusolver.py?

### ISSUE THREAD

**Issue by laytonjb** [lebedov/scikit-cuda#234]
I think this is related to #171 but I can't find a solution.

I am failing to run my program that starts with some standard imports.

test.py

import pycuda.driver as cuda
import pycuda.autoinit
import pycuda.gpuarray as gpuarray
import pycuda.cumath
from pycuda.compiler import SourceModule
import numpy as np
from skcuda import linalg
linalg.init()

Error output:

Traceback (most recent call last):
  File "test3.py", line 9, in <module>
    linalg.init()
  File "/home/laytonjb/anaconda2/lib/python2.7/site-packages/skcuda/misc.py", line 177, in init
    from . import cusolver
  File "/home/laytonjb/anaconda2/lib/python2.7/site-packages/skcuda/cusolver.py", line 51, in <module>
    raise OSError('cusolver library not found')
OSError: cusolver library not found

All pyCUDA and scikit-CUDA dependencies are installed freshly and all CUDA paths are set up according CUDA documentation. I'm using CUDA-9.0 and scikit-cuda 0.5.1.

Thanks!

**Comment by lebedov** [comment]
Please use the latest revision on GitHub - it has been updated to support 9.0.
