### ISSUE TITLE
CULA libraries needed?

### ISSUE THREAD

**Issue by laytonjb** [lebedov/scikit-cuda#235]
I just installed the latest from github (1/5/18). I tried a simple SVD computation:

import pycuda.autoinit
import pycuda.gpuarray as gpuarray
import numpy as np
import skcuda.linalg as linalg

linalg.init()
a = np.random.randn(9,6) + 1j*np.random.randn(9,6)
a = np.asarray(a, np.complex64)

a_gpu = gpuarray.to_gpu(a)

u_gpu, s_gpu, yh_gpu = linalg.svd(a_gpu, 'S', 'S')

When I executed the script I get the following error:

Traceback (most recent call last):
  File "test1.py", line 12, in <module>
    u_gpu, s_gpu, yh_gpu = linalg.svd(a_gpu, 'S', 'S')
  File "/home/laytonjb/anaconda2/lib/python2.7/site-packages/scikit_cuda-0.5.2-py2.7.egg/skcuda/linalg.py", line 340, in svd
    raise NotImplementedError('CULA not installed')
NotImplementedError: CULA not installed

Do I need to install CULA? If so, any pointers to where I download it?

Jeff

**Comment by lebedov** [comment]
As noted in the svd [docstring](http://scikit-cuda.readthedocs.io/en/latest/generated/skcuda.linalg.svd.html#skcuda-linalg-svd), one may use either CULA or CUSOLVER as the backend library for svd computation. Unfortunately, CULA is only available to [premium tier users of Celerity Tools](http://scikit-cuda.readthedocs.io/en/latest/install.html#installation-dependencies) (it used to be freely available for academic use when I initially developed scikit-cuda), so you will have to make do with CUSOLVER (whose svd implementation is - or was - [less then stellar](https://devtalk.nvidia.com/default/topic/830894/cusolverdncgesvd-performance-vs-mkl/)) if you don't wish to pay for Celerity.
