### ISSUE TITLE
CuSolver Import Error

### ISSUE THREAD

**Issue by ifelismino** [lebedov/scikit-cuda#241]
Hello.

I'm running Python 3.5, on Fedora 21, with CUDA 8.0 and PyCuda 2017.1.1. with the current git version of skcuda.

I'm running to this problem when initializing Linalg. 

AttributeError: /opt/hpc/soft/tools/cuda-8.0/lib64/libcusolver.so: undefined symbol: cusolverDnCreateSyevjInfo

Thanks

**Comment by lebedov** [comment]
Do you mean the exception is raised when you run `skcuda.linalg.init`? Can you post the entire trace of the exception so that I can see where it is being raised? The `cusolverDnCreateSyevjInfo` function should be disabled if you don't have CUDA 9.0+ installed, but the error you indicated shouldn't occur.

**Comment by ifelismino** [comment]
No. The exception is raised when doing the from skcuda import linalg.

Here's the whole exception message

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-ba4da90d6b36> in <module>()
      3 import numpy as np
      4 import ctypes
----> 5 from skcuda import linalg
      6 linalg.init()

~/.conda/envs/cuConda/lib/python3.5/site-packages/scikit_cuda-0.5.2-py3.5.egg/skcuda/linalg.py in <module>()
     23 from . import cublas
     24 from . import cudart
---> 25 from . import misc
     26 from . import cusolver
     27 

~/.conda/envs/cuConda/lib/python3.5/site-packages/scikit_cuda-0.5.2-py3.5.egg/skcuda/misc.py in <module>()
     36 
     37 try:
---> 38     from . import cusolver
     39     _has_cusolver = True
     40 except (ImportError, OSError):

~/.conda/envs/cuConda/lib/python3.5/site-packages/scikit_cuda-0.5.2-py3.5.egg/skcuda/cusolver.py in <module>()
    282 
    283 if cudart._cudart_version >= 9000:
--> 284     _libcusolver.cusolverDnCreateSyevjInfo.restype = int
    285     _libcusolver.cusolverDnCreateSyevjInfo.argtypes = [ctypes.c_void_p]
    286 

~/.conda/envs/cuConda/lib/python3.5/ctypes/__init__.py in __getattr__(self, name)
    362         if name.startswith('__') and name.endswith('__'):
    363             raise AttributeError(name)
--> 364         func = self.__getitem__(name)
    365         setattr(self, name, func)
    366         return func

~/.conda/envs/cuConda/lib/python3.5/ctypes/__init__.py in __getitem__(self, name_or_ordinal)
    367 
    368     def __getitem__(self, name_or_ordinal):
--> 369         func = self._FuncPtr((name_or_ordinal, self))
    370         if not isinstance(name_or_ordinal, int):
    371             func.__name__ = name_or_ordinal

AttributeError: /opt/hpc/soft/tools/cuda-8.0/lib64/libcusolver.so: undefined symbol: cusolverDnCreateSyevjInfo

**Comment by Paul0629** [comment]
I met the error 'cusolver library not found' and I really don't know how to deal with it. Someone says it works when changing '_libcusolver = ctypes.cdll.LoadLibrary(_libcusolver_libname)' to '_libcusolver = ctypes.cdll.LoadLibrary("/usr/local/cuda-7.5/targets/x86_64-linux/lib/"+_libcusolver_libname)
'. But my cuda8.0 doesn't have a path like that and I don't why.

**Comment by lebedov** [comment]
What does the following print? Given that the exception is raised at [cusolver.py:284](https://github.com/lebedov/scikit-cuda/blob/master/skcuda/cusolver.py#L284 ), it seems you may have CUDA 9.* installed somewhere:

```python
import skcuda.cudart as cudart
print(cudart.cudaRuntimeGetVersion())
```

**Comment by ifelismino** [comment]
Hello, this is what the code gives. Something I forgot to mention, in case it causes the issue, was that PyCuda was installed in a local directory and is set with EXPORT PYTHONPATH.

---------------------------------------------------------------------------
cudaErrorInsufficientDriver               Traceback (most recent call last)
<ipython-input-3-ed408a1a3214> in <module>()
      2 import pycuda.autoinit
      3 import skcuda.cudart as cudart
----> 4 print(cudart.cudaRuntimeGetVersion())

~/.conda/envs/cuConda/lib/python3.5/site-packages/scikit_cuda-0.5.2-py3.5.egg/skcuda/cudart.py in cudaRuntimeGetVersion()
    803     version = ctypes.c_int()
    804     status = _libcudart.cudaRuntimeGetVersion(ctypes.byref(version))
--> 805     cudaCheckStatus(status)
    806     return version.value
    807 

~/.conda/envs/cuConda/lib/python3.5/site-packages/scikit_cuda-0.5.2-py3.5.egg/skcuda/cudart.py in cudaCheckStatus(status)
    559     if status != 0:
    560         try:
--> 561             raise cudaExceptions[status]
    562         except KeyError:
    563             raise cudaError('unknown CUDA error %s' % status)

cudaErrorInsufficientDriver:

**Comment by ifelismino** [comment]
It's working now. There was problems with the environment path set before when loading CUDA. Thanks!

**Comment by lebedov** [comment]
Great!
