### ISSUE TITLE
Issue with Magma 2.3.0. KeyError: 'A'

### ISSUE THREAD

**Issue by ifelismino** [lebedov/scikit-cuda#247]
Hi, I tried using Magma 2.3.0 with PyCuda 2017.1.1 ver and skcuda current github egg. And it reads magma fine, but trying to do the svd example yields to an error. Is 2.3.0 supported or do I need to go to an older version of MAGMA? Thank you.

`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-8d570fc34f1c> in <module>()
     28 # Set up workspace:
     29 Lwork = magma.magma_sgesvd_buffersize('A', 'A', m, n, x.ctypes.data, m, s.ctypes.data,
---> 30                                       u.ctypes.data, m, vh.ctypes.data, n)
     31 workspace = np.zeros(Lwork, np.float32)
     32 

~/.conda/envs/cuConda/lib/python3.4/site-packages/skcuda/magma.py in magma_sgesvd_buffersize(jobu, jobvt, m, n, a, lda, s, u, ldu, vt, ldvt)
   1158 def magma_sgesvd_buffersize(jobu, jobvt, m, n, a, lda, s, u, ldu, vt, ldvt):
   1159     return _magma_gesvd_buffersize(jobu, jobvt, m, n, a, lda, s, u, ldu, vt,
-> 1160                                    ldvt, magma_sgesvd, np.float32)
   1161 
   1162 def magma_dgesvd_buffersize(jobu, jobvt, m, n, a, lda, s, u, ldu, vt, ldvt):

~/.conda/envs/cuConda/lib/python3.4/site-packages/skcuda/magma.py in _magma_gesvd_buffersize(jobu, jobvt, m, n, a, lda, s, u, ldu, vt, ldvt, func, dtype)
   1153     func(jobu, jobvt, m, n,
   1154          int(a), lda, int(s), int(u), ldu,
-> 1155          int(vt), ldvt, int(work.ctypes.data), -1)
   1156     return int(work[0])
   1157 

~/.conda/envs/cuConda/lib/python3.4/site-packages/skcuda/magma.py in magma_sgesvd(jobu, jobvt, m, n, a, lda, s, u, ldu, vt, ldvt, work, lwork)
   2744     """
   2745 
-> 2746     jobu = _vec_conversion[jobu]
   2747     jobvt = _vec_conversion[jobvt]
   2748     info = c_int_type()

KeyError: 'A'`

**Comment by lebedov** [comment]
_vec_conversion doesn't seem to be being populated properly for versions >= 1.5.0; investigating further.
