### ISSUE TITLE
cufft library not found

### ISSUE THREAD

**Issue by tdmvch** [lebedov/scikit-cuda#250]
I'm trying to initialize CUDA for MNE package, but have issue. I'm using Windows 10 x64, Anaconda environment with Python 2.7 and CUDA 9.1.84. Skcuda 0.5.1 and pycuda (2017.1.1+cuda9185) are installed, but executing mne.cuda.init_cuda() to initialize CUDA gives 'OSError: cufft library not found'.
Cufft library exist in CUDA folder.
I think, there might be problem with PATH, but I need guidence to solve it.

I will provide any necessary information if needed.

**Comment by lebedov** [comment]
Please try the latest revision on GitHub.

**Comment by lebedov** [comment]
Closing - feel free to reopen if the issue still persists.
