### ISSUE TITLE
2d Fourier Transform does not match numpy.fft.fft2

### ISSUE THREAD

**Issue by themightyoarfish** [lebedov/scikit-cuda#253]
I realize that `skcuda.fft.fft` computes redundancy-free FT while `np.fft.fft2` computes the full output of the same size as the input image.
```
import numpy as np
np.random.seed(0)
import pycuda.autoinit
import pycuda
from skcuda import fft


N = 4
array = np.random.randint(255, size=(N, N))
array_gpu = pycuda.gpuarray.to_gpu(array)
ft = np.fft.fft2(array)
print(ft)

ft_gpu = pycuda.gpuarray.empty((N//2+1, N//2+1), dtype=np.complex64)
plan = fft.Plan((N, N), np.float32, np.complex64)
fft.fft(array_gpu, ft_gpu, plan)
print(ft_gpu.get())
```
The result is that the shapes are different (obviously), but the values are completely unrelated in value and magnitude. Maybe I am misunderstanding something, but this does not make sense to me.

**Comment by lebedov** [comment]
The default dtype of `numpy.random.randint` is `numpy.int` - try converting the array to `numpy.float32` before transferring it to the GPU.
