### ISSUE TITLE
`skcuda.linalg.dot` doesn't work since `misc._global_cublas_allocator` is `None`

### ISSUE THREAD

**Issue by themightyoarfish** [lebedov/scikit-cuda#254]
In my installation, `skcuda.misc._global_cublas_allocator` is always `None`. I notice this problem when trying to use `skcuda.linalg.dot`. It fails here:
```
   1052             alloc = misc._global_cublas_allocator
   1053             if x_gpu.strides[1] > x_gpu.strides[0]: # F order
   1054                 out = gpuarray.empty((m, n), x_gpu.dtype, order="F", allocator=alloc)
```
Since the `GPUArray` constructor attempts to `__call__()` the allocator. What could be the cause of this?

**Comment by themightyoarfish** [comment]
It appears one must call `skcuda.misc.init()` first, didn't see it was mentioned anywhere, may have overlooked it.

**Comment by lebedov** [comment]
Yes - CUBLAS needs a valid handle in order to operate, hence the need for `skcuda.misc.init`.
