### ISSUE TITLE
magma_dgetrf_gpu Access Violation

### ISSUE THREAD

**Issue by tinyfx** [lebedov/scikit-cuda#256]
I am using Magma 2.4.0 and Python 3.6 on Windows. 

The following code  results in: OSError: exception: access violation writing 0x0000000B0540000

```
import numpy as np
import pycuda.autoinit
import pycuda.gpuarray as gpuarray
import skcuda.magma as magma

magma.magma_init()  
n = 100              
a = np.asarray(np.random.rand(n, n), order='F', )
a_gpu = gpuarray.to_gpu(a)
ipiv_gpu = gpuarray.empty((n,), np.int32, order='F')
magma.magma_dgetrf_gpu(n ,n, a_gpu.gpudata, n, ipiv_gpu.gpudata)
magma.magma_finalize()
```

Other functions seem to work OK. Any help in trying to solve this would be really appreciated!

**Comment by lebedov** [comment]
`ipiv` should be allocated in host memory, not on the GPU (and should therefore be passed to `magma_dgetrf_gpu` as `ipiv.ctypes.data`).
