### ISSUE TITLE
Weird Can't import skcuda.linalg.PCA problem

### ISSUE THREAD

**Issue by davidsonic** [lebedov/scikit-cuda#259]
Hi, I encountered this weird import error for PCA module. I installed scikit-cuda successfully without any error and I could import other modules. However, when I tried to import PCA using the example snippet, I got the following error:
![image](https://user-images.githubusercontent.com/15846113/44625400-1c301a80-a8bd-11e8-982e-a24c48765a0b.png)

OS platform: ubuntu16.04
Python version: 3.6 from anaconda3
CUDA version: 8.0
PyCUDA version and scikit-cuda were installed using pip of anaconda3:
pip3 install scikit-cuda.

Did I miss anything? Thanks!

**Comment by lebedov** [comment]
Please try the latest revision on GitHub.
