### ISSUE TITLE
missing wrapper for cublas.cublasSgetrsBatched 

### ISSUE THREAD

**Issue by bburas** [lebedov/scikit-cuda#264]
I'm trying to solve many small linear systems using LU factorization  where A is 10x10 and B is 10x1. The batch number = 1e5.

I have been able to call cublas.cublasSgetrfBatched() but there is no cublas.cublasSgetrsBatched.
I tried to add the wrapper but I get a seg fault when I try to call it:

cublas._libcublas.cublasSgetrsBatched.restype = int
cublas._libcublas.cublasSgetrsBatched.argtypes = [cublas._types.handle,
                                          ctypes.c_int,
                                          ctypes.c_int,
                                          ctypes.c_int,
                                          ctypes.c_void_p,
                                          ctypes.c_int,
                                          ctypes.c_void_p,
                                          ctypes.c_void_p,
                                          ctypes.c_int,
                                          ctypes.c_void_p,
                                          ctypes.c_int]
def cublasSgetrsBatched(handle,trans,n,nrhs, A, lda, P, B, ldb, info, batchSize):

    status = cublas._libcublas.cublasSgetrsBatched(handle, cublas._CUBLAS_OP[trans],
                                                   n,nrhs,
                                                   int(A), lda, int(P),
                                                   int(B), ldb,
                                                   int(info), batchSize)
    cublas.cublasCheckStatus(status)

I'm running cuda 9.2, cublas 9020, python 3.6, rhel7.4 scikit 5.2 (from source as of today)

**Comment by bburas** [comment]
Here's my complete code test. I used bptrs from the skcuda test_cublas.py . I'm not sure if this is correct.
I have been able to use  cublas.cublasSgemmBatched with expected results. There is also a StridedBatched I may want to try.

import numpy as np
from numpy import float32
from timeit import default_timer as timer

import ctypes
from numpy.ctypeslib import ndpointer

import scipy.linalg

import skcuda
import pycuda.autoinit
import pycuda.driver as drv
from pycuda import driver, compiler, gpuarray, tools

from skcuda import cusolver, cublas
def bptrs(a):
    """
    Pointer array when input represents a batch of matrices.
    """

    return gpuarray.arange(a.ptr,a.ptr+a.shape[0]*a.strides[0],a.strides[0],
                dtype=cublas.ctypes.c_void_p)

def cuda_solve_cublasBatched(a,b):
    l = 10
    m = a.shape[0]
    rows = m
    cols = m

    # just make 10 copies
    A = np.stack([a for _ in range (l)],axis=0)
    B = np.stack([b for _ in range (l)],axis=0)

    print("A=%s B=%s"%(A.shape,B.shape))
    # create cusolver handle - bind stream
    h = cublas.cublasCreate()

    s = timer()

    a_gpu = gpuarray.to_gpu(A)
    b_gpu = gpuarray.to_gpu(B)
    a_arr = bptrs(a_gpu)
    b_arr = bptrs(b_gpu)

    devInfo = gpuarray.zeros(1, np.int32)
    # pivot off?
    devIpiv = gpuarray.zeros((l,m), np.int32)
    
    # step 3 query working space of getrf
    #worksize = cusolver.cusolverDnSgetrf_bufferSize(handle, rows, rows, a_gpu.ptr, 0)
    #print("LU worksize:", worksize)


    # step 4: LU factorization 
    print("LU decomp batched ")
    cublas.cublasSgetrfBatched(h,
                               m, a_arr.gpudata, m,
                               devInfo.gpudata, devIpiv.gpudata, l)
 
    print(devInfo)

    #LU = a_gpu.get()
    #print("LU = %s"%LU)
    #print("devinfo = %s"%devInfo.get())

    # Step 5: solve nxn matrix after LU-factoring with getrf
    #crash here
    cublas.cublasSgetrsBatched(h, 
                        'n',
                        m, 1, 
                        b_arr.gpudata, m,
                        devIpiv.gpudata,# pivot
                        a_arr.gpudata, m,
                        devInfo.gpudata, l)

    print("completes getrs")
    #print(solve_status, devInfo)
    c = b_gpu.get()[0]
    cublas.cublasDestroy(h)
    return c


def main():
    rows = 3
    cols = 3
    m = 3
    lda = m
    ldb = m

    a = np.array( [[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,10.0]], np.float32)      
    b = np.array( [1.0,2.0,3.0], np.float32)


    print("A = %s"%a)
    print("b = %s"%b)

    s = timer()
    for i in range(0,100):
        c = scipy.linalg.solve(a, b)
    print("time = %f"%(timer()-s))
    print("scipi.linalg.solve c = %s"%c)

    s = timer()
    c = cuda_solve_cublasBatched(a,b)
    print("time = %f"%(timer()-s))
    print("cublas c = %s"%c)


main()

**Comment by lebedov** [comment]
Please [format your code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) so that it can be cut and pasted without having to reconstruct its indenting.

**Comment by bburas** [comment]
I updated my comment.
Also attached.

**Comment by lebedov** [comment]
The `info` param of cublas*getrsBatched needs to be a [host variable, not a device variable](https://docs.nvidia.com/cuda/cublas/#cublas-lt-t-gt-getrsbatched); you should create a variable `info = ctypes.c_int()` and then pass it to the wrapper with `ctypes.byref(info)`. I updated the wrappers to not attempt to cast it to int.
