### ISSUE TITLE
wrong GEEV wrapper interfaces for magma 

### ISSUE THREAD

**Issue by wingkitlee0** [lebedov/scikit-cuda#265]
Hi, I found that some of the eigenvalue solver interfaces in magma.py are simply wrong (indeed, they look unfinished). I have fixed the basic versions (sgeev, dgeev, cgeev, zgeev) but I believe the multi-gpu ones (e.g., sgeev_m) are still not working. I can submit a pull-request shortly.

Details:
1. the argument types for magma_sgeev and magma_dgeev are incorrect.
2. arguments jobvl and jobvr needs conversion in sgeev, dgeev, cgeev, zgeev (possibily in _m variant as well)

Info:
scikit-cuda commit ab0d3e22fc301d880e9221313524b4b18d136076

**Comment by lebedov** [comment]
Thanks for the fix - merged.
