### ISSUE TITLE
skcuda version check fails with cuda 10.0

### ISSUE THREAD

**Issue by bburas** [lebedov/scikit-cuda#268]
rhel7
cuda 10.0 installed from run script
python 3.6
skcuda 5.2 installed from source from git

see runtime error:
"NotImplementedError: CUBLAS 5.0 required"

Looks like  cublas._get_cublas_version() needs update for 10.0.

**Comment by lebedov** [comment]
Added 10.0.

**Comment by bburas** [comment]
Thanks for the fast response!

Unfortunately I still have the problem,
See line 313
if _cublas_version >= int(self.vi):
10.0 is interpreted as 1000 (prob should be 10000?) while minimum, version
is 5000.

**Comment by lebedov** [comment]
Fixed.
