### ISSUE TITLE
cublas library not found

### ISSUE THREAD

**Issue by cegprakash** [lebedov/scikit-cuda#269]
## Problem

step 1: install `scikit-cuda==0.5.2`
step 2: Just do ` import skcuda.linalg as linalg  `

## Error
  File "C:\Users\cegprakash\.virtualenvs\similarity_articles-JuZA6FGA\lib\site-packages\skcuda\linalg.py", line 23, in <module>
    from . import cublas
  File "C:\Users\cegprakash\.virtualenvs\similarity_articles-JuZA6FGA\lib\site-packages\skcuda\cublas.py", line 55, in <module>
    raise OSError('cublas library not found')
OSError: cublas library not found

## Environment

* OS platform : Windows 10
* Python version : 3.6.3
* CUDA version :  V10.0.130 (Installed it from https://developer.nvidia.com/cuda-downloads)
* PyCUDA version : 2018.1.1
* scikit-cuda version : 0.5.2

**Comment by cegprakash** [comment]
related closed issues #202 #179

**Comment by cegprakash** [comment]
I also tried
CUDA version : V8.0.60

I got a similar error

```
  File "C:\Users\cegprakash\.virtualenvs\similarity_articles-JuZA6FGA\lib\site-packages\skcuda\linalg.py", line 11, in <module>
    from pycuda.tools import context_dependent_memoize
  File "C:\Users\cegprakash\.virtualenvs\similarity_articles-JuZA6FGA\lib\site-packages\pycuda\tools.py", line 34, in <module>
    import pycuda.driver as cuda
  File "C:\Users\cegprakash\.virtualenvs\similarity_articles-JuZA6FGA\lib\site-packages\pycuda\driver.py", line 5, in <module>
    from pycuda._driver import *  # noqa
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by cegprakash** [comment]
tried 'scikit-cuda==0.5.1'
same issue persists : cublas library not found

**Comment by lebedov** [comment]
Re the error you obtained with CUDA 10, try the latest revision on GitHub. If that doesn't work, check your CUDA installation; skcuda uses Python ctypes' built-in shared library loader to look for libraries - if a library isn't found, it may need to be added to whatever path or registry entry Win10 uses to search for libraries.

The error you obtained with CUDA 8 is a pycuda error which suggests that pycuda wasn't built/installed properly.

**Comment by lebedov** [comment]
According to NVIDIA's [online docs for Windows](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html), the default CUDA installation path is C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0 (the actual path may differ on your system depending on how you installed it) - the libraries might be in a subfolder. Unfortunately, I don't have a Win10 system with a GPU in it to confirm.

**Comment by cegprakash** [comment]
Cublas.h is available here C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include and
cublas64_80.dll is available in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin
I also have cublas.lib here C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64

What else could be the problem?

**Comment by cegprakash** [comment]
if anyone made it work on windows 10, plz let me know python version, cuda version and scikit-cuda version

**Comment by lebedov** [comment]
For Win10, try adding C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64 to your PATH environmental variable (assuming that CUDA 10 was installed in the default location).

**Comment by cegprakash** [comment]
I only have a bin folder in this path : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0

I do not have a lib folder.

**Comment by cegprakash** [comment]
I face the same error even after adding this path to environment variable

**Comment by lebedov** [comment]
I assume that the CUBLAS dll files are actually located in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64 ? If so, not sure why Python can't see them.

**Comment by cegprakash** [comment]
the dll was that there in 8.0 version (as I uninstalled 10.0). I removed that comment as soon as I found it. But even after adding environment variable I got the same error.

**Comment by cegprakash** [comment]
if anyone made it work on windows 10, plz let me know python version, cuda version and scikit-cuda version

**Comment by lebedov** [comment]
You may wish to inquire on stackoverflow or some similar forum, as the failure of Python ctypes to find a shared library is not specific to skcuda.

**Comment by cegprakash** [comment]
This issue is only windows specific. (Just tested in Ubuntu + Nvidia where it runs fine)

**Comment by ataudt** [comment]
I had the same error on similar specs:
OSError: cublas library not found
- Windows 10
- python 3.7.0
- CUDA (nvcc) V10.0.130
- pycuda==2018.1.1

and got it running by installing scikit-cuda-0.5.3 from github. The cublas DLL was called cublas64_100.dll and this was not expected in scikit-cuda-0.5.2

**Comment by lebedov** [comment]
@ataudt Yes - that's why I [suggested](https://github.com/lebedov/scikit-cuda/issues/269#issuecomment-438137804) the latest GitHub revision. That said, I'm not sure why adding the path to the dll on the Windows system @cegprakash described to PATH didn't fix the problem on his system; is there a CUDA-related path in your system's PATH variable?

**Comment by bryantChhun** [comment]
Could someone provide instructions on how to get version 0.5.3 from github?  I'd very much prefer not to build from source.

**Comment by lebedov** [comment]
@bryantChhun If you have `setuptools` installed, you can install the latest version from GitHub as follows:
```
pip install -e git://github.com/lebedov/scikit-cuda#egg=scikit-cuda
```
Or, just clone the repository and install as follows:
```
git clone https://github.com/lebedov/scikit-cuda
cd scikit-cuda
python setup.py install
```

**Comment by bryantChhun** [comment]
FYI, installing latest version (0.5.3) solved this problem for me.

**Comment by ystallonne** [comment]
scikit-cuda version : 0.5.3
CUDA v10.1
Windows 10
PyCUDA version : 2018.1.1
Python 3.7.3

raise OSError('cublas library not found')
facing this issue again...

It is trying to load cublas64_40.dll, but I have cublas64_10.dll.

**Comment by lebedov** [comment]
@ystallonne Not sure why NVIDIA decided to name the Windows CUBLAS library the way they did - updated cublas.py to look for cublas64_10.dll. Try the latest revision on GitHub.

**Comment by ystallonne** [comment]
Thank you, @lebedov 
I got the latest revision, the cublas is solved, but now I get an error for the cusolver library:

raise OSError('cusolver library not found')

I ran "python setup.py test" and I see that cufft is probably next:

raise OSError('cufft library not found')

**Comment by lebedov** [comment]
@ystallonne Ah, yes - updated cusolver.py, cufft.py, and cusparse.py accordingly.

**Comment by zengzhi2015** [comment]
Hei, I find out a bug in 'cublus.py'.
```
        _libcublas_libname_list = ['cublas.dll'] + \
            ['cublas64_%s.dll' % (int(v) if v >= 10 else int(10*v)) for v in _version_list]
```
When I print out the list, I get the following:
```
['cublas.dll', 'cublas64_10.dll', 'cublas64_10.dll', 'cublas64_92.dll', 'cublas64_91.dll', 'cublas64_90.dll', 'cublas64_80.dll', 'cublas64_75.dll', 'cublas64_70.dll', 'cublas64_65.dll', 'cublas64_60.dll', 'cublas64_55.dll', 'cublas64_50.dll', 'cublas64_40.dll']
```
But what I really have in windows is 'cublas64_100.dll'. So, it is adviced that the code should be changed to
```
        _libcublas_libname_list = ['cublas.dll'] + \
            ['cublas64_%s.dll' % int(10*v) for v in _version_list]
```

**Comment by lebedov** [comment]
@zengzhi2015 You presumably are using CUDA 10.0. It seems that the shared library was named cublas64_100.dll in CUDA 10.0 and cublas64_10.dll in CUDA 10.1. I updated the files to explicitly list the shared library file names used on Linux and Windows.

**Comment by lebedov** [comment]
I'm locking this issue because folks keep on tagging on comments to it; this complicates debugging because each scenario may potentially be different. For users who encounter problems that seem similar to this one in the future, please submit a new issue.
