### ISSUE TITLE
The FFT in-place scale cache is not context aware

### ISSUE THREAD

**Issue by npyoung** [lebedov/scikit-cuda#273]
## Problem

When you set `scale=True` in a call to `fft`, `ifft`, `rfft`, etc, the kernel that performs the scaling is cached ([code here](https://github.com/lebedov/scikit-cuda/blob/master/skcuda/fft.py#L151)). However, the cache is not CUDA context-aware, so if you call `fft` with scaling in CUDA context 1, then call `fft` in context 2 (with scaling), the cache gets a hit and you pull up the compiled kernel from context 1, resulting in a CUDA error.

This could be fixed by including the active CUDA context in the hash used by the cache.

## Environment

* Ubuntu 16.04
* Python 3.6
* CUDA 10.0 (Amazon Deep Learning AMI)
* PyCUDA version 2018.1.1
* scikit-cuda version 0.5.2

**Comment by lebedov** [comment]
Fixed.
