### ISSUE TITLE
cublas library not found

### ISSUE THREAD

**Issue by nouxu1** [lebedov/scikit-cuda#277]
when I imported skucuda.linalg I get the OSError: cublas library not found

environment:
scikit-cuda version : 0.5.2
CUDA v10.0
Windows 10
PyCUDA version : 2019.1
Python 3.6.3

**Comment by nouxu1** [comment]
hello
I am using:
scikit-cuda version : 0.5.2
CUDA v10.0
Windows 10
PyCUDA version : 2019.1
Python 3.6.3

when I imported skucuda.linalg I get the OSError: cublas library not found

**Comment by lebedov** [comment]
Can you please try the latest revision on GitHub? If it works for you, I'll upload a new release of skcuda on pypi.

**Comment by lebedov** [comment]
I uploaded a new release on pypi.
