### ISSUE TITLE
Perhaps a bug on PCA fit_transform method?

### ISSUE THREAD

**Issue by fjgmoya** [lebedov/scikit-cuda#281]
@lebedov, @nmerrill67, thank you for your work. I'm a rookie about Python code, but I wonder weather or not there is a **bug at the line 220 of fit_transform code  inside [PCA class](https://github.com/lebedov/scikit-cuda/blob/master/skcuda/linalg.py#L220).**

Reading carefully Andrecut's algorithm about GS-PCA, it seems this last  matrix product operation (**cuGer**) is **INSIDE** of the main "for" loop. But reading the code, the indentation suggests this product is **OUT** the loop, and then it executes only one time, (not "k" times as the number of principal components).

Is it a mistake from me? Are you agree? 
Thanks in advance!!

Plaform: not important at this time, it's a concept issue about a possible difference between algorithm and code implementation.

**Comment by nmerrill67** [comment]
@fjgmoya You are absolutely correct, thanks. I must have messed up the indenting when fixing changing the tabs to four spaces. I am issuing another PR right now.

**Comment by lebedov** [comment]
Thanks for identifying - and thanks to @nmerrill67 for the fix.
