### ISSUE TITLE
cublas version detection bugs

### ISSUE THREAD

**Issue by bmerry** [lebedov/scikit-cuda#300]
## Problem
While trying to debug why skcuda.cublas wasn't working for me after updating to CUDA 11 (turns out my driver is too old) I found some bugs in the version detection code:

- [This line](https://github.com/lebedov/scikit-cuda/blob/11f286e5cf185ffe4d1c096db2c8aed7d7cc7035/skcuda/utils.py#L117) fails on Python 3 because it uses float division and passes the result to `range`. It needs to use `//`.

- In CUDA 11, the SONAME for libcublas is `libcublas.so.11`, with no minor number, so [this regex](https://github.com/lebedov/scikit-cuda/blob/11f286e5cf185ffe4d1c096db2c8aed7d7cc7035/skcuda/cublas.py#L279) fails to match.

## Environment

- Ubuntu 18.04
- Python 3.6.6
- CUDA 11, installed from the runfile downloaded from NVIDIA
- pycuda 2019.1.2
- scikit-cuda 0.5.3

**Comment by lebedov** [comment]
Fixed.
