### ISSUE TITLE
Possible error in documentation for PCA

### ISSUE THREAD

**Issue by LucaCappelletti94** [lebedov/scikit-cuda#301]
## Problem
Hello and thank you for creating this package.

I have just stumbled across this and I see if the CUDA-enabled PCA was faster, but I saw that the documentation contains a possible typo, or at least raises some doubt about what is implemented as PCA.

Specifically, [the PCA documentation states](https://scikit-cuda.readthedocs.io/en/latest/generated/skcuda.linalg.PCA.html):

> The algorithm implemented here was first implemented with CUDA in [Andrecut, 2008]. It performs **NONLINEAR** dimensionality reduction for a data matrix, mapping the data to a lower-dimensional space of K.

Now, PCA, in its vanilla version is absolutely linear. If this is a Kernel PCA, or a Multilinear PCA or any of the other methods based on PCA that are non-linear I believe it should be mentioned in the documentation.

I believe the solution to this is, after verification, to either replace the term non-linear with linear or to properly explain what aspects of non-linearity are at play here and what, specifically, is the non-linear implementation of PCA used.

Again, thank you for creating this package and keep up the good work!

**Comment by nmerrill67** [comment]
Hello, if you look at the most recent code in the master branch, you will see that I have corrected that typo.

**Comment by LucaCappelletti94** [comment]
Ok, thanks!
