### ISSUE TITLE
skcuda.misc.mean

### ISSUE THREAD

**Issue by SimoneRegaldo** [lebedov/scikit-cuda#312]
## Problem
I am new to scikit cuda and I am trying to calculate the mean of the rows of a 2D array using the Colab GPU.

import numpy as np
import pycuda.driver as cuda
import pycuda.autoinit
import pycuda.gpuarray as gpuarray
import skcuda.misc as misc

test=np.array([[1,1,1],
              [2,2,2],
              [3,3,3]]).astype(np.float32)
test_gpu=gpuarray.to_gpu(test)

result_gpu=misc.mean(test_gpu,axis=0,keepdims=True)

print(result_gpu.get())

The skcuda.misc.mean performs the mean on the flattened array (axis=None) with any problems, but if I try to define 'axis' in order to calculate the means of the rows, I get an error:

/usr/local/lib/python3.6/dist-packages/pycuda/gpuarray.py in __init__(self, shape, dtype, allocator, base, gpudata, strides, order)
    208         if gpudata is None:
    209             if self.size:
    210                 self.gpudata = self.allocator(self.size * self.dtype.itemsize)
    211             else:
    212                 self.gpudata = None

TypeError: 'NoneType' object is not callable

I do not know if I made some mistakes in my code or there is a problem with the function. Could you help me, please?

## Environment
* Python version: 3.6
* PyCUDA version: 2020.1
* scikit-cuda version: 0.5.3

**Comment by lebedov** [comment]
You need to initialize the libraries skcuda uses by including the line

```python
misc.init()
```

before you call any of the other skcuda functions.

**Comment by SimoneRegaldo** [comment]
Thank you very much! Everything is working 👍🏻
