### ISSUE TITLE
skcuda.linalg.cho_solve API different than in scipy.linalg

### ISSUE THREAD

**Issue by vallis** [lebedov/scikit-cuda#323]
`scipy.linalg.cho_solve` expects the output of `scipy.linalg.cho_factor` as the first argument; by contrast, `skcuda.linalg.cho_solve` takes a matrix as first argument, calls cholesky on it, then solves the equation.

Is this by design?

**Comment by lebedov** [comment]
cho_solve as [originally contributed](https://github.com/lebedov/scikit-cuda/commit/c3e536f7) was designed to directly wrap the CULA function that did not assume a Cholesky-factorized input. When support for using CUSOLVER as a backend was added later, the function was updated to call cho_factor to preserve the original interface and avoid breaking whatever code depended on it.
