### ISSUE TITLE
Can not install pycuda to Azure Container Instances with v100

### ISSUE THREAD

**Issue by rifaterdemsahin** [lebedov/scikit-cuda#327]
**In the container**
python3.8 -m pip install scikit-cuda

**Error**
![image](https://user-images.githubusercontent.com/5270036/144478295-3e03e9f7-ae06-4faf-94b4-7afc651caba2.png)

**Comment by lebedov** [comment]
This seems to be a problem involving installation of pycuda, not scikit-cuda itself. You may wish to bring up the issue on pycuda's [discussion board](https://github.com/inducer/pycuda/discussions) to whether its developer can assist - not sure why it isn't installing properly.
