### ISSUE TITLE
Missing `cublasSetMatrix` compared with CUDA documentation

### ISSUE THREAD

**Issue by SuperbTUM** [lebedov/scikit-cuda#328]
## Problem

I read CUDA documentation about scikit-cuda, I found there is a function named `cublasSetMatrix`, which can transfer a submatrix from host to device. But it disappears in skcuda implementation. Not knowing if it is because this is an unnecessary function. Thanks in advance.

## Environment

OS platform: Google Colab Linux 5.4
Python version: 3.7
CUDA version: 11.2
PyCUDA version: 2021.1
scikit-cuda version: 0.5.3

**Comment by lebedov** [comment]
I didn't deem it necessary to wrap that function because PyCUDA already can handle most host -> device memory setting use cases.
