### ISSUE TITLE
drop scikits namespace, rename package to scikit-cuda

### ISSUE THREAD

**Issue by lebedov** [lebedov/scikit-cuda#45]
Many scikits (e.g., scikits-image, scikit-learn, statsmodels) have dropped the scikits namespace to simplify usage; the scikits.cuda namespace package should be simplified to skcuda. Renaming the package to scikit-cuda would also be desirable.

**Comment by untom** [comment]
FYI, I think the renaming is a good idea (simply because typing `skcuda` is much more convenient :) ). However, the current solution does not work in Python3. I've toyed around with it a bit, but haven't come up with how to do this cleanly in Py3 yet.

**Comment by lebedov** [comment]
Rearranging the order of the imports in `skcuda/__init__.py` seems to make it work in Py3 (see dfe4cef). Can you please confirm?

**Comment by untom** [comment]
Interesting! Yes, the imports now work in Py3. However, I've noticed that the following fails (in both Py2 and Py3):

    import skcuda
    skcuda.__version__    ## -> AttributeError: 'module' object has no attribute '__version__'

**Comment by lebedov** [comment]
Fixed in e5cd3ff.

**Comment by lebedov** [comment]
Package renamed.
