### ISSUE TITLE
OSError: libcula_lapack.so, libcula_lapack_basic.so, libcula.so not found

### ISSUE THREAD

**Issue by jantogni** [lebedov/scikit-cuda#81]
Hello,

I installed the last version of Scikits.cuda from github source code, but when I try to run svd_demo.py I get the following error: 

OSError: libcula_lapack.so, libcula_lapack_basic.so, libcula.so not found

I have installed cula in /usr/local/cula:
doc
examples
include
lib -> here I have the libcula_lapack_basic.so
lib64

Should I edit some configuration file or something?

In advance thank you very much, best regards,

**Comment by ShanLuo** [comment]
Hi @jantogni , where did you download CULA? I checked the webpage of CULA but got this " As of June 14, 2013, CULA will no longer be offered as an individually licensed product. Cluster and distribution licenses will be available. Please contact us for additional details." Is there any other way to obtain CULA?

@lebedov Any advice?

Thanks in advance!

**Comment by lebedov** [comment]
@ShanLuo, I'm not aware of any legal way to download CULA at the present time. Some of the functionality of CULA is present in NVIDIA's CUSOLVER library, while other comparable functions are in MAGMA. What function(s) in CULA do you need?

**Comment by ShanLuo** [comment]
@lebedov. Thanks for your reply. For now, I want to use CULA to do the SVD computation, as shown in one of the demo examples of scikit-cuda. Is there any way to do it using CUSOLVER or MAGMA instead? Thanks.

**Comment by lebedov** [comment]
@ShanLuo: yes, `skcuda.linalg.svd()` in the latest revision of scikit-cuda on GitHub supports the use of CUSOLVER instead of CULA - just set lib='cusolver' when you call the function.

**Comment by ShanLuo** [comment]
@lebedov Great! Thanks for your advice! But I don't how to I set lib='cusolver'.. Can you give me more details? Thanks.

**Comment by ShanLuo** [comment]
@lebedov I think I find the solution: skcuda.linalg.svd(a_gpu, jobu=’A’, jobvt=’A’, lib=’cula’). It works, thanks!
