### ISSUE TITLE
Mac OSX Mavericks 10.9.5 can't find CULA

### ISSUE THREAD

**Issue by stevertaylor** [lebedov/scikit-cuda#82]
I'm consistently getting this problem

raise OSError('%s not found' % _load_err)
OSError: libcula_lapack.dylib, libcula_core.dylib not found

I had to change the default library names in cula.py since CULA 16 gives libcula_lapack.dylib, libcula_core.dylib for Mac OSX 10.9.5. CULA is installed and works. All CULA libraries are included in the DYLD_LIBRARY_PATH. CUBLAS is working fine, but the scikits.cuda just can't find CULA, even though the relevant .dylib files are in the library path.

**Comment by lebedov** [comment]
Closing old ticket - please reopen if this still is a problem.
