### ISSUE TITLE
failed installation of scikits.cuda: nvcc not in path

### ISSUE THREAD

**Issue by marcoippolito** [lebedov/scikit-cuda#83]
Hi,
the installation of scikits.cuda via pip failed: "nvcc not in path"

marco@marco-All-Series:~$ sudo pip install scikits.cuda
Downloading/unpacking scikits.cuda
  Downloading scikits.cuda-0.042.tar.gz (97kB): 97kB downloaded
  Running setup.py (path:/tmp/pip_build_root/scikits.cuda/setup.py) egg_info for package scikits.cuda

Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python2.7/dist-packages (from scikits.cuda)
Downloading/unpacking pycuda>=0.94.2 (from scikits.cuda)
  Downloading pycuda-2014.1.tar.gz (1.6MB): 1.6MB downloaded
  Running setup.py (path:/tmp/pip_build_root/pycuda/setup.py) egg_info for package pycuda
    **\* WARNING: nvcc not in path.
    *************************************************************
    **\* I have detected that you have not run configure.py.
    *************************************************************
    **\* Additionally, no global config files were found.
    **\* I will go ahead with the default configuration.
    **\* In all likelihood, this will not work out.
    ***
    **\* See README_SETUP.txt for more information.
    ***
    **\* If the build does fail, just re-run configure.py with the
    **\* correct arguments, and then retry. Good luck!
    *************************************************************
    **\* HIT Ctrl-C NOW IF THIS IS NOT WHAT YOU WANT
    *************************************************************
Continuing in 1 seconds...   ..  
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pycuda/setup.py", line 216, in <module>
        main()
      File "/tmp/pip_build_root/pycuda/setup.py", line 88, in main
        conf["CUDA_INC_DIR"] = [join(conf["CUDA_ROOT"], "include")]
      File "/usr/lib/python2.7/posixpath.py", line 77, in join
        elif path == '' or path.endswith('/'):
    AttributeError: 'NoneType' object has no attribute 'endswith'
    Complete output from command python setup.py egg_info:
    **\* WARNING: nvcc not in path.

---

**\* I have detected that you have not run configure.py.

---

**\* Additionally, no global config files were found.

**\* I will go ahead with the default configuration.

**\* In all likelihood, this will not work out.

---

**\* See README_SETUP.txt for more information.

---

**\* If the build does fail, just re-run configure.py with the

**\* correct arguments, and then retry. Good luck!

---

**\* HIT Ctrl-C NOW IF THIS IS NOT WHAT YOU WANT

---

Continuing in 1 seconds...    

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pycuda/setup.py", line 216, in <module>

```
main()
```

  File "/tmp/pip_build_root/pycuda/setup.py", line 88, in main

```
conf["CUDA_INC_DIR"] = [join(conf["CUDA_ROOT"], "include")]
```

  File "/usr/lib/python2.7/posixpath.py", line 77, in join

```
elif path == '' or path.endswith('/'):
```

AttributeError: 'NoneType' object has no attribute 'endswith'

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pycuda
Storing debug log for failure in /home/marco/.pip/pip.log

Yesterday I had the same problem with Theano.
Before installing some packages with Anaconda distribution and then removing Anaconda (didn't want to rely on proprietary distribution), everything with Theano went fine.
But just right after anaconda's removal, exactly the same error's message appeared.
For Theano I solved the problem, putting the path into .theanorc file (theano's configuration file-"tableau de bord" file).

Any hints to solve the problem for scikits.cuda?

Looking forward to your kind help.
Kind regards.
Marco

**Comment by DarrVeter** [comment]
running comman without sudo solved my problem. also you can change secure path, got explanation here https://askubuntu.com/questions/428234/nvcc-not-found-but-only-when-using-sudo
